# Generated by Django 2.2.10 on 2020-03-06 11:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic_page', '0001_initial'),
        ('base', '0003_auto_20200306_1141'),
        ('guide_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidepagetopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='topic_page.TopicPage', verbose_name='Select a Topic'),
        ),
        migrations.AddField(
            model_name='guidepagecontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Contact'),
        ),
        migrations.AddField(
            model_name='guidepagecontact',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='guide_page.GuidePage'),
        ),
        migrations.AddField(
            model_name='guidepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage'),
        ),
    ]
