# Generated by Django 2.2.12 on 2020-05-05 19:19

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contact', '0002_contact_location_page'),
        ('department_page', '0001_initial'),
        ('base_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaReleasePage',
            fields=[
                ('janisbasepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_page.JanisBasePage')),
                ('body', wagtail.core.fields.RichTextField(blank=True, verbose_name='Body')),
                ('body_ar', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Body')),
                ('body_en', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Body')),
                ('body_es', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Body')),
                ('body_vi', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Body')),
                ('contact', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contact.Contact')),
                ('written_for_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='department_page.DepartmentPage')),
            ],
            options={
                'abstract': False,
            },
            bases=('base_page.janisbasepage',),
        ),
    ]
