# Generated by Django 2.2.12 on 2020-06-18 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('base_page', '0002_add_pageviewpermissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDocumentPage',
            fields=[
                ('janisbasepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_page.JanisBasePage')),
                ('date', models.DateField(null=True, verbose_name='Document date')),
                ('document_title', models.CharField(max_length=255, null=True, verbose_name='Document title')),
                ('document_title_ar', models.CharField(max_length=255, null=True, verbose_name='Document title')),
                ('document_title_en', models.CharField(max_length=255, null=True, verbose_name='Document title')),
                ('document_title_es', models.CharField(max_length=255, null=True, verbose_name='Document title')),
                ('document_title_vi', models.CharField(max_length=255, null=True, verbose_name='Document title')),
                ('authoring_office', models.CharField(max_length=255, null=True, verbose_name='Authoring office of document')),
                ('authoring_office_ar', models.CharField(max_length=255, null=True, verbose_name='Authoring office of document')),
                ('authoring_office_en', models.CharField(max_length=255, null=True, verbose_name='Authoring office of document')),
                ('authoring_office_es', models.CharField(max_length=255, null=True, verbose_name='Authoring office of document')),
                ('authoring_office_vi', models.CharField(max_length=255, null=True, verbose_name='Authoring office of document')),
                ('summary', models.TextField(verbose_name='Document summary')),
                ('summary_ar', models.TextField(null=True, verbose_name='Document summary')),
                ('summary_en', models.TextField(null=True, verbose_name='Document summary')),
                ('summary_es', models.TextField(null=True, verbose_name='Document summary')),
                ('summary_vi', models.TextField(null=True, verbose_name='Document summary')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Document')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='Name of Document')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name of Document')),
                ('name_es', models.CharField(max_length=255, null=True, verbose_name='Name of Document')),
                ('name_vi', models.CharField(max_length=255, null=True, verbose_name='Name of Document')),
                ('document', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Document [en]')),
                ('document_es', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Document [es]')),
            ],
            options={
                'abstract': False,
            },
            bases=('base_page.janisbasepage',),
        ),
    ]
