# Generated by Django 2.2.12 on 2020-06-18 21:46

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('official_documents_list', '0001_initial'),
        ('official_documents_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='authoring_office',
            field=models.CharField(blank=True, default='opo', max_length=255, verbose_name='Authoring office of document'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='authoring_office_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Authoring office of document'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='authoring_office_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Authoring office of document'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='authoring_office_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Authoring office of document'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='authoring_office_vi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Authoring office of document'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Document date'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Document [en]'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='document_title',
            field=models.CharField(blank=True, default='title', max_length=255, verbose_name='Document title'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='document_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document title'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='document_title_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document title'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='document_title_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document title'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='document_title_vi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Document title'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Name of Document'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Document'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='name_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Document'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Document'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='name_vi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Document'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='summary',
            field=models.TextField(blank=True, verbose_name='Document summary'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='summary_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Document summary'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='summary_en',
            field=models.TextField(blank=True, null=True, verbose_name='Document summary'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='summary_es',
            field=models.TextField(blank=True, null=True, verbose_name='Document summary'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='summary_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Document summary'),
        ),
        migrations.CreateModel(
            name='OfficialDocumentListDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('official_document_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='official_documents_list.OfficialDocumentList', verbose_name='Select an Official Document List')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_document_list', to='official_documents_page.OfficialDocumentPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
