# Generated by Django 2.2.11 on 2020-03-24 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('official_documents_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdocumentpageofficialdocument',
            name='document_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Document [es]'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpageofficialdocument',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Document [en]'),
        ),
    ]
