# Generated by Django 2.2.13 on 2020-07-07 02:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_page', '0001_initial'),
        ('base_page', '0003_add_publish_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contenttypes', '0002_remove_content_type_name'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('official_documents_page', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OfficialDocumentPage',
            new_name='OfficialDocumentPageOld',
        ),
    ]
