# Generated by Django 2.2.13 on 2020-07-08 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('base_page', '0003_add_publish_fields'),
        ('official_documents_page', '0002_auto_20200707_0214'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDocumentPage',
            fields=[
                ('janisbasepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_page.JanisBasePage')),
                ('date', models.DateField(blank=True, null=True, verbose_name='Document date')),
                ('authoring_office', models.CharField(blank=True, max_length=255, verbose_name='Authoring office of document')),
                ('authoring_office_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Authoring office of document')),
                ('authoring_office_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Authoring office of document')),
                ('authoring_office_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='Authoring office of document')),
                ('authoring_office_vi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Authoring office of document')),
                ('summary', models.TextField(blank=True, verbose_name='Document summary')),
                ('summary_ar', models.TextField(blank=True, null=True, verbose_name='Document summary')),
                ('summary_en', models.TextField(blank=True, null=True, verbose_name='Document summary')),
                ('summary_es', models.TextField(blank=True, null=True, verbose_name='Document summary')),
                ('summary_vi', models.TextField(blank=True, null=True, verbose_name='Document summary')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name of Document')),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Document')),
                ('name_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Document')),
                ('name_es', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Document')),
                ('name_vi', models.CharField(blank=True, max_length=255, null=True, verbose_name='Name of Document')),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Document [en]')),
                ('document_es', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Document [es]')),
            ],
            options={
                'abstract': False,
            },
            bases=('base_page.janisbasepage',),
        ),
    ]
