# Generated by Django 2.2.12 on 2020-06-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official_documents_page', '0002_auto_20200618_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialdocumentpage',
            name='document_title',
        ),
        migrations.RemoveField(
            model_name='officialdocumentpage',
            name='document_title_ar',
        ),
        migrations.RemoveField(
            model_name='officialdocumentpage',
            name='document_title_en',
        ),
        migrations.RemoveField(
            model_name='officialdocumentpage',
            name='document_title_es',
        ),
        migrations.RemoveField(
            model_name='officialdocumentpage',
            name='document_title_vi',
        ),
    ]
