# Generated by Django 2.2.14 on 2020-08-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('official_documents_page', '0006_auto_20200713_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdocumentpage',
            name='body',
            field=models.TextField(blank=True, verbose_name='Document body'),
        ),
        migrations.AddField(
            model_name='officialdocumentpage',
            name='body_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Document body'),
        ),
        migrations.AddField(
            model_name='officialdocumentpage',
            name='body_en',
            field=models.TextField(blank=True, null=True, verbose_name='Document body'),
        ),
        migrations.AddField(
            model_name='officialdocumentpage',
            name='body_es',
            field=models.TextField(blank=True, null=True, verbose_name='Document body'),
        ),
        migrations.AddField(
            model_name='officialdocumentpage',
            name='body_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Document body'),
        ),
    ]
