# Generated by Django 2.2.15 on 2020-09-14 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('official_documents_page', '0009_auto_20200909_1529'),
        ('official_documents_page', '0009_auto_20200827_1552'),
    ]

    operations = [
    ]
