# Generated by Django 2.2.16 on 2020-11-24 19:19

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('official_documents_page', '0011_auto_20201002_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='summary',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Document summary'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='summary_ar',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Document summary'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='summary_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Document summary'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='summary_es',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Document summary'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='summary_vi',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Document summary'),
        ),
    ]
