dist: trusty
services:
- docker
sudo: required
env:
  global:
  - secure: QJeEG45/JCwm2PIr5QkOTz2uMtN5fijBtQVdUpDhBKjrYO3P8izasP9S0GebXclX/JYT450S5eAsWifo8Ju7W5U33mteBQ879TqrryPx8thDnSB/ZH0oyA+1fzdANwjOfXU5YBr4yoNELhDFS7THX9PLC9khYo6OT+bk2BuO1CmSUcC2Nz9qoJnsdlCYkoqIkDqRjTDT1l9Hftr0qshzvwogS7vtEFuXGr2dBfNVjW9cVVglU/PMItvih3SPCvfA2d3HvgYgml5h49ZWpWBjQnyrxaBROGk6tNoSBxYfYQOR2lT6ciuOzk9X0nyl6eU9NRPH63sZMGd3I/aodmwpq69y+ay6kivC5J8xbLGV0mKMLGCw21MCN4q9ISuyPiS3gvPEUfr+TxtDyZBXzR4O/ECt54jV3RZWZkSBDpg300hPLD4+EtrczCwkWZbDry84rAL85Z1eKtRFpkgbb0n1kFsmVMYwt9L9TH6JyCRlEcqc9cI9SIBcN4Z3gO/MAN0xC42+DzSadZf44L2bDVrdCeu3zyLFk2yz0NVBm1+beWEyQVrLCuucc53ec5UBCialprtYarM3QNhRJ0S2Ob3xVrThLJ+2sArQ0A14+o6ficOg1fqAg0MNYJ8vSqqJ6fK/72XTnQrVq8KEolvMxqzzEia++R3DUo7WHkvC1etRhZY=
  - secure: lIBGSdWS+jTZB5crPKmifVRBxV+MCmaurtl6nEnL0MSd5jiPplAOuXrJ2c8hR2TI+fO1Yjp9PEYWSKmFx5JzWkjESVzLfupMnPNsaiyUktHiRtmjYIIsOvWftLz0N35gboZL6PfnVOPatfQ/v1zJLoYVpp/uhlDHw6hn48cmQj+XYl+NTrhTvfZKb3VjCrHho+2M6y1t1tp9Yz+ynmIT+pfqVD7RpzDWvx0wBLEr2zhGIOYfOP6uUKhCXZWdXK18nDk3HrE6ZJsSTKsXJ9EzVKCywvPXUWoT2rKhenqj8n1caSCpSzYvic2ylx6L47OrGTm1TbaI9Ozvpe6hCTnpZXB5LdFCgitdkSQekFcS2lKNkw0m9Nx9DHcmlqnraUhkY/HTC8oY3ffQYJhiU3vq1FbeyRp/2xsmCryct1P9JN2i/IlppvpCQvdXH2xEjzr1a75tDwRISAjjZskeGXFKOIZ6lGhwItOfHp/mBJI03oGyF8oPUJVsZnE0etRJaVtmVmSD+7mzXU+43Pmzd6aH5njVWQggqTUxPrG+6vqgWtqoEwna2x7E5J24JXYH+xt9GK01pOZ8Veh4dc/A+1Sll42byO33j3B5sbka89+zETDwmAowGXuB54AipCtv93Oof+eaM1BGLq3Jl7NPeWgVL/N6BlcYruuRPAEgMLRytv8=
jobs:
  include:
  - stage: Testing Phase
    script:
    - echo "We're good as gold"
  - stage: Building Image & Deployment to Registry
    script:
    - echo "Heroku Login: $HEROKU_LOGIN"
    - docker login --username=$HEROKU_LOGIN --password=$HEROKU_API_KEY registry.heroku.com
    - docker build --rm=false -t registry.heroku.com/joplin-personal/web .
    - docker push registry.heroku.com/joplin-personal/web:latest
