#
# Using Generic, Travis CI defaults to Ruby and Python can slow down the process.
#

language: generic
dist: trusty
services:
- docker
sudo: required
env:
  global:
  - JOPLIN_TARGET: joplin-personal
  - JOPLIN_IMAGE_NAME: joplin-base
  - secure: ff2pKZbz5sgBZj+LBezVatSNgLuhafO18kGqZpVelb6wPXF0E1KZpbC0/i1IpZql2rtJY3Y+Y/7mla5B2q+lj8biFrg7NmkfVVtmDIPFpxw88RRpqRZ+ig9btE6qIpYGlV3PNAHETdGN7NrTK9qG2bQZAuWDZwBdfrl+WMKTbZplJL8ZJcIMtehDcAwtNuWJI9hh7RA+W5mwmd8pO2CwhoF2dvOG5REadNhAG87E4XE7kO4jhqacY2nbAr5ElbYXvdkwChkmsFuZkMtobAE62/JzMYY2bMQV8sie6WsivMkWVeATo/9pozJnrjp4Ohfk+MOmLAxUk8tymaN3QkrAM6VVvLDaA4wz9sAeh9sZLJYiX1jOHcGsJUbsC++YER/Dpm4GoZiP6zWFhcx7Mu7xazCuDrpMRs+ApTv+7gZT3MbjyVFkzWnoz2KBirQ+KgNHokC9fuZJeYu8TjuM8Sv8u/36qxhkj2IoA2PAhcFgfZfrgFTObV3Rk/IQWJRZ4NOnqrWajN2aaztcNeqpbk23dEH2PVwsLTHDOtPKMMCp/Uu58fdNfD5DSORU/AQdQ4SdVeTPoOGImhvlwMDc6Wwcm4ecNIYohJQW7hMGp07bksVyaBkUBnMRlvqlL7Qlh2Bkx65lTi3U78zogNIGGgcPBxGVFvWjEfVYTDFW2dI3T7E=

#
# Deployment Process
#
jobs:
  include:
  - stage: Dependencies stage
    script:
    - curl https://cli-assets.heroku.com/install-ubuntu.sh | sh
  - stage: Testing stage
    script:
    - echo "Heroku Login:$HEROKU_LOGIN"
    - echo "Deployment Details ( TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$TRAVIS_PULL_REQUEST,
      BRANCH=$TRAVIS_PULL_REQUEST_BRANCH, MESSAGE=$TRAVIS_COMMIT_MESSAGE )"
  - stage: Build and release stage
    script:
    - source ./.travis/heroku-helper.sh
    - docker login --username=_ --password=$HEROKU_API_KEY registry.heroku.com
    - docker build -t $JOPLIN_IMAGE_NAME .
    - docker tag $JOPLIN_IMAGE_NAME registry.heroku.com/$JOPLIN_TARGET/web
    - docker push registry.heroku.com/$JOPLIN_TARGET/web
    - WEB_DOCKER_IMAGE_ID=$(docker images -q $JOPLIN_IMAGE_NAME)
    - echo $WEB_DOCKER_IMAGE_ID
    - heroku_release $JOPLIN_TARGET $JOPLIN_IMAGE_NAME
  - stage: Post-release stage
    script:
    - heroku run -a $JOPLIN_TARGET -- /app/migrate-load-data.sh
