version: '3.7'
services:
  janis:
    image: $DOCKER_TAG_JANIS
    ports:
      - "${JANIS_APP_HOST_PORT}:80"
    environment:
      CMS_API: $CMS_API
      CMS_MEDIA: $CMS_MEDIA
    depends_on:
      - "app"
