version: '3'
services:
  joplin:
    build: .
    ports:
     - "8000:80"
    volumes:
      - ".:/app"
    environment:
      LOAD_DATA: $LOAD_DATA
      HEROKU_KEY: $HEROKU_KEY
      DEBUG: 1
      GUNICORN_CMD_ARGS: "--reload  --reload-engine=poll"
      JANIS_URL: http://localhost:3000
      STYLEGUIDE_URL: https://cityofaustin.github.io/digital-services-style-guide
      WATCH_LOCAL: "on"
  joplinassets:
    build:
      context: .
      dockerfile: Dockerfile.assets
    volumes:
      - "./joplin:/app/joplin"
    entrypoint: sh docker-entrypoint.watchassets.sh
