version: '3.7'
# Override gunicorn CMD
services:
  app:
    environment:
      "DEPLOYMENT_MODE": "LOCAL"
    entrypoint: "./docker-entrypoint.sh"
    command: ["echo", "\"No server needed at this step of the migration test: exiting app\""]
