version: '3'
services:
  joplindb:
    container_name: "joplin_db"
    image: postgres:10
    ports:
     - "${JOPLIN_DB_PUBLIC_PORT}:5432" # 5432:5432
    environment:
      POSTGRES_DB: 'joplin'
      POSTGRES_USER: 'joplin'
  joplin:
    container_name: "joplin_app"
    build:
      context: .
      dockerfile: Dockerfile.local
    ports:
     - "${JOPLIN_APP_PUBLIC_PORT}:80" # 8000:80
    volumes:
     - ".:/app"
    environment:
      LOAD_DATA: $LOAD_DATA
      HEROKU_KEY: $HEROKU_KEY
      DEBUG: 1
      GUNICORN_CMD_ARGS: "--reload  --reload-engine=poll"
      JANIS_URL: http://localhost:3000
      STYLEGUIDE_URL: https://cityofaustin.github.io/digital-services-style-guide
      DEPLOYMENT_MODE: "LOCAL"
      DATABASE_URL: "postgres://joplin@joplindb:${JOPLIN_DB_PUBLIC_PORT}/joplin"
    depends_on:
     - "joplindb"
  # joplinassets:
  #   container_name: "$JOPLIN_ASSETS_CONTAINER_NAME"
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.assets
  #   volumes:
  #     - "./joplin:/app/joplin"
  #   entrypoint: sh docker-entrypoint.watchassets.sh
