# Generated by Django 2.2.9 on 2020-01-23 01:32

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_notes', wagtail.core.fields.RichTextField(blank=True, verbose_name='Notes for authors (Not visible on the resident facing site)')),
                ('coa_global', models.BooleanField(default=False, verbose_name='Make this a top level page')),
                ('description', models.TextField(blank=True, verbose_name='Write a description of this page')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Write a description of this page')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Write a description of this page')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Write a description of this page')),
                ('description_vi', models.TextField(blank=True, null=True, verbose_name='Write a description of this page')),
                ('date', models.DateField(null=True, verbose_name='Event date')),
                ('start_time', models.TimeField(null=True)),
                ('end_time', models.TimeField(null=True)),
            ],
            options={
                'permissions': [('view_extra_panels', 'Can view extra panels'), ('view_snippets', 'Can view snippets'), ('add_snippets', 'Can add snippet'), ('delete_snippets', 'Can delete snippet')],
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
