# Generated by Django 2.2.9 on 2020-01-29 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eventpagefee',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='eventpagefee',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
