# Generated by Django 2.2.9 on 2020-01-23 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
