# Generated by Django 2.2.9 on 2020-01-23 03:11

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200123_0134'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='location',
            field=wagtail.core.fields.StreamField([('city_location', wagtail.core.blocks.StructBlock([('location_page', wagtail.core.blocks.PageChooserBlock(label='Location', page_type=['locations.LocationPage'])), ('additional_details', wagtail.core.blocks.TextBlock(label='Field for additional details, such as room number'))])), ('remote_location', wagtail.core.blocks.StructBlock([('street', wagtail.core.blocks.TextBlock(label='Street')), ('unit', wagtail.core.blocks.TextBlock(label='Unit')), ('city', wagtail.core.blocks.TextBlock(label='City')), ('state', wagtail.core.blocks.TextBlock(label='State')), ('country', wagtail.core.blocks.TextBlock(label='Country')), ('zip', wagtail.core.blocks.TextBlock(label='ZIP')), ('additional_details', wagtail.core.blocks.TextBlock(label='Field for additional details, such as room number'))]))], blank=True),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Event date'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description',
            field=models.TextField(blank=True, verbose_name='Full description of the event'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Full description of the event'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Full description of the event'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Full description of the event'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Full description of the event'),
        ),
    ]
