# Generated by Django 2.2.9 on 2020-01-30 03:49

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_auto_20200129_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='canceled',
            field=models.BooleanField(default=False, help_text='Canceling an event will not unpublish it, but it will display the event as canceled.', verbose_name='Cancel this event'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Full description of the event', verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_ar',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Full description of the event', null=True, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_en',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Full description of the event', null=True, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Full description of the event', null=True, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_vi',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Full description of the event', null=True, verbose_name='Long description'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='location_blocks',
            field=wagtail.core.fields.StreamField([('city_location', wagtail.core.blocks.StructBlock([('location_page', wagtail.core.blocks.PageChooserBlock(classname='do-not-hide', label='Location', page_type=['locations.LocationPage'])), ('additional_details_en', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [en]', required=False)), ('additional_details_es', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [es]', required=False)), ('additional_details_ar', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [ar]', required=False)), ('additional_details_vi', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [vi]', required=False))])), ('remote_location', wagtail.core.blocks.StructBlock([('name_en', wagtail.core.blocks.TextBlock(label='Name of venue [en]')), ('name_es', wagtail.core.blocks.TextBlock(label='Name of venue [es]', required=False)), ('name_ar', wagtail.core.blocks.TextBlock(label='Name of venue [ar]', required=False)), ('name_vi', wagtail.core.blocks.TextBlock(label='Name of venue [vi]', required=False)), ('street', wagtail.core.blocks.TextBlock(label='Street', required=False)), ('unit', wagtail.core.blocks.TextBlock(label='Unit', required=False)), ('city', wagtail.core.blocks.TextBlock(label='City', required=False)), ('state', wagtail.core.blocks.TextBlock(label='State', required=False)), ('zip', wagtail.core.blocks.TextBlock(label='ZIP', required=False)), ('additional_details_en', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [en]', required=False)), ('additional_details_es', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [es]', required=False)), ('additional_details_ar', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [ar]', required=False)), ('additional_details_vi', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [vi]', required=False))]))], blank=True, verbose_name='Add location of event'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='registration_url',
            field=models.URLField(blank=True, help_text='The URL where the resident may register for the event, if needed', verbose_name='Registration'),
        ),
    ]
