# Generated by Django 2.2.9 on 2020-01-23 03:16

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200123_0311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpage',
            old_name='location',
            new_name='locations',
        ),
        migrations.AddField(
            model_name='eventpage',
            name='locations_ar',
            field=wagtail.core.fields.StreamField([('city_location', wagtail.core.blocks.StructBlock([('location_page', wagtail.core.blocks.PageChooserBlock(label='Location', page_type=['locations.LocationPage'])), ('additional_details', wagtail.core.blocks.TextBlock(label='Field for additional details, such as room number'))])), ('remote_location', wagtail.core.blocks.StructBlock([('street', wagtail.core.blocks.TextBlock(label='Street')), ('unit', wagtail.core.blocks.TextBlock(label='Unit')), ('city', wagtail.core.blocks.TextBlock(label='City')), ('state', wagtail.core.blocks.TextBlock(label='State')), ('country', wagtail.core.blocks.TextBlock(label='Country')), ('zip', wagtail.core.blocks.TextBlock(label='ZIP')), ('additional_details', wagtail.core.blocks.TextBlock(label='Field for additional details, such as room number'))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='locations_en',
            field=wagtail.core.fields.StreamField([('city_location', wagtail.core.blocks.StructBlock([('location_page', wagtail.core.blocks.PageChooserBlock(label='Location', page_type=['locations.LocationPage'])), ('additional_details', wagtail.core.blocks.TextBlock(label='Field for additional details, such as room number'))])), ('remote_location', wagtail.core.blocks.StructBlock([('street', wagtail.core.blocks.TextBlock(label='Street')), ('unit', wagtail.core.blocks.TextBlock(label='Unit')), ('city', wagtail.core.blocks.TextBlock(label='City')), ('state', wagtail.core.blocks.TextBlock(label='State')), ('country', wagtail.core.blocks.TextBlock(label='Country')), ('zip', wagtail.core.blocks.TextBlock(label='ZIP')), ('additional_details', wagtail.core.blocks.TextBlock(label='Field for additional details, such as room number'))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='locations_es',
            field=wagtail.core.fields.StreamField([('city_location', wagtail.core.blocks.StructBlock([('location_page', wagtail.core.blocks.PageChooserBlock(label='Location', page_type=['locations.LocationPage'])), ('additional_details', wagtail.core.blocks.TextBlock(label='Field for additional details, such as room number'))])), ('remote_location', wagtail.core.blocks.StructBlock([('street', wagtail.core.blocks.TextBlock(label='Street')), ('unit', wagtail.core.blocks.TextBlock(label='Unit')), ('city', wagtail.core.blocks.TextBlock(label='City')), ('state', wagtail.core.blocks.TextBlock(label='State')), ('country', wagtail.core.blocks.TextBlock(label='Country')), ('zip', wagtail.core.blocks.TextBlock(label='ZIP')), ('additional_details', wagtail.core.blocks.TextBlock(label='Field for additional details, such as room number'))]))], blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpage',
            name='locations_vi',
            field=wagtail.core.fields.StreamField([('city_location', wagtail.core.blocks.StructBlock([('location_page', wagtail.core.blocks.PageChooserBlock(label='Location', page_type=['locations.LocationPage'])), ('additional_details', wagtail.core.blocks.TextBlock(label='Field for additional details, such as room number'))])), ('remote_location', wagtail.core.blocks.StructBlock([('street', wagtail.core.blocks.TextBlock(label='Street')), ('unit', wagtail.core.blocks.TextBlock(label='Unit')), ('city', wagtail.core.blocks.TextBlock(label='City')), ('state', wagtail.core.blocks.TextBlock(label='State')), ('country', wagtail.core.blocks.TextBlock(label='Country')), ('zip', wagtail.core.blocks.TextBlock(label='ZIP')), ('additional_details', wagtail.core.blocks.TextBlock(label='Field for additional details, such as room number'))]))], blank=True, null=True),
        ),
    ]
