# Generated by Django 2.2.9 on 2020-02-11 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_auto_20200130_0349'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventPageRelatedDepartments',
        ),
    ]
