# Generated by Django 2.2.9 on 2020-01-23 03:20

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200123_0316'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventpage',
            name='locations_ar',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='locations_en',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='locations_es',
        ),
        migrations.RemoveField(
            model_name='eventpage',
            name='locations_vi',
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='locations',
            field=wagtail.core.fields.StreamField([('city_location', wagtail.core.blocks.StructBlock([('location_page', wagtail.core.blocks.PageChooserBlock(label='Location', page_type=['locations.LocationPage'])), ('additional_details_en', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [en]')), ('additional_details_es', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [es]', required=False)), ('additional_details_ar', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [ar]', required=False)), ('additional_details_vi', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [vi]', required=False))])), ('remote_location', wagtail.core.blocks.StructBlock([('street', wagtail.core.blocks.TextBlock(label='Street')), ('unit', wagtail.core.blocks.TextBlock(label='Unit')), ('city', wagtail.core.blocks.TextBlock(label='City')), ('state', wagtail.core.blocks.TextBlock(label='State')), ('country', wagtail.core.blocks.TextBlock(label='Country')), ('zip', wagtail.core.blocks.TextBlock(label='ZIP')), ('additional_details_en', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [en]')), ('additional_details_es', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [es]', required=False)), ('additional_details_ar', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [ar]', required=False)), ('additional_details_vi', wagtail.core.blocks.TextBlock(label='Any other necessary location details, such as room number [vi]', required=False))]))], blank=True),
        ),
    ]
