# Generated by Django 2.2.10 on 2020-02-26 21:55

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_auto_20200219_1901'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Full description of the event', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_ar',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Full description of the event', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_en',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Full description of the event', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Full description of the event', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_vi',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Full description of the event', null=True, verbose_name='Description'),
        ),
    ]
