# Generated by Django 2.2.10 on 2020-02-28 01:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200226_2155'),
        ('events', '0004_delete_eventpagerelateddepartments'),
    ]

    operations = [
    ]
