# Generated by Django 2.2.9 on 2020-01-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20200123_0320'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpage',
            old_name='locations',
            new_name='location_blocks',
        ),
    ]
