# Generated by Django 2.2.9 on 2020-01-23 04:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_eventpage_event_is_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventPageFee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10)),
                ('fee_label', models.TextField(blank=True, verbose_name='Label (kids, adults, seniors, etc.)')),
                ('fee_label_ar', models.TextField(blank=True, null=True, verbose_name='Label (kids, adults, seniors, etc.)')),
                ('fee_label_en', models.TextField(blank=True, null=True, verbose_name='Label (kids, adults, seniors, etc.)')),
                ('fee_label_es', models.TextField(blank=True, null=True, verbose_name='Label (kids, adults, seniors, etc.)')),
                ('fee_label_vi', models.TextField(blank=True, null=True, verbose_name='Label (kids, adults, seniors, etc.)')),
                ('page', modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='fees', to='events.EventPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
