# Generated by Django 2.2.9 on 2020-01-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventpagefee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpagefee',
            name='fee_label',
            field=models.CharField(blank=True, max_length=255, verbose_name='Label (kids, adults, seniors, etc.)'),
        ),
        migrations.AlterField(
            model_name='eventpagefee',
            name='fee_label_ar',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Label (kids, adults, seniors, etc.)'),
        ),
        migrations.AlterField(
            model_name='eventpagefee',
            name='fee_label_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Label (kids, adults, seniors, etc.)'),
        ),
        migrations.AlterField(
            model_name='eventpagefee',
            name='fee_label_es',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Label (kids, adults, seniors, etc.)'),
        ),
        migrations.AlterField(
            model_name='eventpagefee',
            name='fee_label_vi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Label (kids, adults, seniors, etc.)'),
        ),
    ]
