# Generated by Django 2.2.9 on 2020-01-23 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_auto_20200123_0438'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='registration_url',
            field=models.URLField(blank=True, verbose_name='The URL where the resident may register for the event, if needed'),
        ),
    ]
