# Generated by Django 2.2.9 on 2020-01-23 05:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200107_2305'),
        ('events', '0011_eventpage_registration_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.Contact'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='event_is_free',
            field=models.BooleanField(default=True, verbose_name='This event is free'),
        ),
        migrations.CreateModel(
            name='EventPageRelatedDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_departments', to='events.EventPage')),
                ('related_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.DepartmentPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
