# Generated by Django 2.2.9 on 2020-01-23 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_auto_20200123_0503'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpage',
            name='cancelled',
            field=models.BooleanField(default=True, verbose_name='Cancel this event'),
        ),
    ]
