# Generated by Django 2.2.9 on 2020-01-23 05:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_eventpage_cancelled'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventpage',
            old_name='cancelled',
            new_name='canceled',
        ),
    ]
