# Generated by Django 2.2.9 on 2020-01-23 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_auto_20200123_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='canceled',
            field=models.BooleanField(default=False, verbose_name='Cancel this event'),
        ),
    ]
