# Generated by Django 2.2.9 on 2020-01-23 07:48

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_auto_20200123_0509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpage',
            name='description',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Full description of the event'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_ar',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Full description of the event'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Full description of the event'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_es',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Full description of the event'),
        ),
        migrations.AlterField(
            model_name='eventpage',
            name='description_vi',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Full description of the event'),
        ),
    ]
