# Generated by Django 2.2.11 on 2020-03-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='janisbasepage',
            name='imported_revision_id',
            field=models.TextField(blank=True),
        ),
    ]
