# Generated by Django 2.2.12 on 2020-05-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0002_add_pageviewpermissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='janisbasepage',
            name='publish_request_enqueued',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='janisbasepage',
            name='publish_request_pk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='janisbasepage',
            name='publish_request_sk',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='janisbasepage',
            name='published',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
