# Generated by Django 2.2.11 on 2020-03-24 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base_page', '0002_janisbasepage_imported_revision_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='janisbasepage',
            name='imported_revision_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
