# Generated by Django 2.2.15 on 2020-08-27 19:30

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pagetag'),
        ('base_page', '0003_add_publish_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='janisbasepage',
            name='tags',
            field=modelcluster.fields.ParentalManyToManyField(related_name='pages', to='base.PageTag'),
        ),
    ]
