# Generated by Django 2.2.15 on 2020-08-27 16:08

from django.db import migrations
import modelcluster.contrib.taggit


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_pagetag_taggedpage'),
        ('base_page', '0003_add_publish_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='janisbasepage',
            name='tags',
            field=modelcluster.contrib.taggit.ClusterTaggableManager(blank=True, help_text='A comma-separated list of tags.', through='base.TaggedPage', to='base.PageTag', verbose_name='Tags'),
        ),
    ]
