# Generated by Django 2.2.12 on 2020-04-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormContainer',
            fields=[
                ('janisbasepagewithtopics_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='topic_page.JanisBasePageWithTopics')),
                ('description', models.TextField(blank=True, verbose_name='Form description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Form description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Form description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Form description')),
                ('description_vi', models.TextField(blank=True, null=True, verbose_name='Form description')),
                ('form_url', models.URLField(blank=True, help_text='This link can be found under Share > "Link to this form on your website or email:"', verbose_name='Enter the URL of your Formstack form')),
                ('form_url_ar', models.URLField(blank=True, help_text='This link can be found under Share > "Link to this form on your website or email:"', null=True, verbose_name='Enter the URL of your Formstack form')),
                ('form_url_en', models.URLField(blank=True, help_text='This link can be found under Share > "Link to this form on your website or email:"', null=True, verbose_name='Enter the URL of your Formstack form')),
                ('form_url_es', models.URLField(blank=True, help_text='This link can be found under Share > "Link to this form on your website or email:"', null=True, verbose_name='Enter the URL of your Formstack form')),
                ('form_url_vi', models.URLField(blank=True, help_text='This link can be found under Share > "Link to this form on your website or email:"', null=True, verbose_name='Enter the URL of your Formstack form')),
            ],
            options={
                'abstract': False,
            },
            bases=('topic_page.janisbasepagewithtopics',),
        ),
    ]
