# Generated by Django 2.2.10 on 2020-03-06 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic_page', '0001_initial'),
        ('form_container', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formcontainertopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='topic_page.TopicPage', verbose_name='Select a Topic'),
        ),
    ]
