version: 2.1

jobs:
  test:
    docker:
      - image: cityofaustin/joplin-ci-deploy:91ad719
    steps:
      - checkout
      - run:
          name: "Test that CLI utilities work"
          command: bash ./.circleci/cli-test.sh
  build:
    docker:
      - image: cityofaustin/joplin-ci-build:91ad719
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run: echo "placeholder for build"
      # - run:
      #     name: "Build Joplin Docker Image"
      #     command: bash ./.circleci/build.sh
  backup_database:
    docker:
      - image: cityofaustin/joplin-ci-deploy:91ad719
    steps:
      - checkout
      - run:
          name: "Backup Database and Store in S3"
          command: bash ./.circleci/backup_database.sh
  create_app:
    docker:
      - image: cityofaustin/joplin-ci-deploy:91ad719
    steps:
      - checkout
      - run:
          name: "Create App for Heroku Pipeline"
          command: bash ./.circleci/create_app.sh
  deploy:
    docker:
      - image: cityofaustin/joplin-ci-deploy:91ad719
    steps:
      - checkout
      - run: echo "placeholder for deploy"
  migrate:
    docker:
      - image: cityofaustin/joplin-ci-deploy:91ad719
    steps:
      - checkout
      - run: echo "placeholder for migrate"

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
      - backup_database:
          requires:
            - test
      # - backup_database:
      #     filters:
      #       branches:
      #         only:
      #           - master
      #           - production
      - create_app:
          requires:
            - test
          filters:
            branches:
              ignore:
                - master
                - production
      - deploy:
          requires:
            - build
            - backup_database
            - create_app
      - migrate:
          requires:
            - deploy
