version: 2.1

jobs:
  test:
    docker:
      - image: cityofaustin/joplin-ci-deploy:91ad719
    steps:
      - checkout
      - run:
          name: "Test that CLI utilities work"
          command: bash ./.circleci/cli-test.sh
  backup_database:
    docker:
      - image: cityofaustin/joplin-ci-deploy:91ad719
    steps:
      - checkout
      - run:
          name: "Backup Database and Store in S3"
          command: bash ./.circleci/backup_database.sh
  create_review_app:
    docker:
      - image: cityofaustin/joplin-ci-deploy:91ad719
    steps:
      - checkout
      - run:
          name: "Create Review App for Heroku Pipeline"
          command: bash ./.circleci/create_review_app.sh
  build_and_release:
    docker:
      - image: cityofaustin/joplin-ci-build:5a25aef
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: "Build Joplin Docker Image"
          command: bash ./.circleci/build.sh
      - run:
          name: "Release Image to Heroku"
          command: bash ./.circleci/release.sh
      - run:
          name: "Run Migrations"
          command: bash ./.circleci/migrate.sh

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - test
      - backup_database:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - production
      - create_review_app:
          requires:
            - test
          filters:
            branches:
              ignore:
                - master
                - production
      - build_and_release:
          requires:
            - backup_database
            - create_review_app
