version: 2.1

jobs:
  test:
    docker:
      - image: cityofaustin/joplin-ci-deploy:91ad719
    steps:
      - checkout
      - run:
          name: "Test that CLI utilities work"
          command: bash ./.circleci/scripts/cli_test.sh
  backup_database:
    docker:
      - image: cityofaustin/joplin-ci-deploy:91ad719
    steps:
      - checkout
      - run:
          name: "Backup Database and Store in S3"
          command: bash ./.circleci/scripts/backup_database.sh
  build_heroku_infrastructure:
    docker:
      - image: cityofaustin/joplin-ci-deploy:91ad719
    steps:
      - checkout
      - run:
          name: "Create App and Database for Heroku Pipeline"
          command: bash ./.circleci/scripts/build_heroku_infrastructure.sh
  set_pr_vars:
    docker:
      - image: cityofaustin/joplin-ci-deploy:91ad719
    steps:
      - checkout
      - run:
          name: "Set environment vars for PR App"
          command: bash ./.circleci/scripts/set_pr_vars.sh
  build_and_release:
    docker:
      - image: cityofaustin/joplin-ci-build:5a25aef
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: "Print App Environment Variables"
          command: bash ./.circleci/scripts/print_vars.sh
      - run:
          name: "Build Joplin Docker Image"
          command: bash ./.circleci/scripts/build_image.sh
      - run:
          name: "Release Image to Heroku"
          command: bash ./.circleci/scripts/release.sh
      - run:
          name: "Run Migrations"
          command: bash ./.circleci/scripts/migrate.sh

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - test
      - backup_database:
          requires:
            - test
          filters:
            branches:
              only:
                - master
                - production
      - build_heroku_infrastructure:
          requires:
            - backup_database
            - test
          filters:
            branches:
              ignore:
                - production
      - set_pr_vars:
          requires:
            - test
            - build_heroku_infrastructure
          filters:
            branches:
              ignore:
                - master
                - production
      - build_and_release:
          requires:
            - backup_database
            - build_heroku_infrastructure
            - set_pr_vars
