version: 2.1

jobs:
  build:
    working_directory: ~/project
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="18.09.6"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run:
          name: "Build Joplin Docker Image"
          command: bash ./.circleci/build.sh

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              # Just for test purposes
              ignore:
                - master
                - production
