version: 2.1

jobs:
  build:
    docker:
      - image: cityofaustin/circleci-build:e56c99c
    steps:
      - checkout
      - setup_remote_docker:
          version: 18.09.3
      - run:
          name: "Build Joplin Docker Image"
          command: bash ./.circleci/build.sh
  backup_database:
    docker:
      - image: cityofaustin/circleci-build:e56c99c
    steps:
      - checkout
      - run: echo "placeholder for backup_database"
  release_to_heroku:
    docker:
      - image: cityofaustin/circleci-build:e56c99c
    steps:
      - checkout
      - run: echo "placeholder for release_to_heroku"
  migrate:
    docker:
      - image: cityofaustin/circleci-build:e56c99c
    steps:
      - checkout
      - run: echo "placeholder for migrate"

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build
      - backup_database:
          filters:
            branches:
              only:
                - master
                - production
      - release_to_heroku:
          requires:
            - build
            - backup_database
      - migrate:
          requires: release_to_heroku
