version: 2.1

jobs:
  build:
    working_directory: ~/project
    machine:
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: "Build Joplin Docker Image"
          command: bash ./.circleci/build.sh

workflows:
  version: 2.1
  build-and-deploy:
    jobs:
      - build:
          filters:
            branches:
              # Just for test purposes
              ignore:
                - master
                - production
