# Build a new version by running:
# docker build -f .circleci/Dockerfile.circleci-build -t cityofaustin/circleci-build:latest .circleci/
# docker push cityofaustin/circleci-build:latest

# use docker 18.09 so we can use BUILDKIT=1
FROM docker:18.09.6

# add bash (for running bash scripts)
RUN apk add --no-cache bash

# add git (to "checkout" code)
RUN apk add --no-cache \
		git \
		openssh-client
