# Generated by Django 2.2.12 on 2020-04-27 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event_page', '0002_eventpagerelatedpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventpagerelatedpage',
            name='page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page', verbose_name='Page where event is displayed'),
        ),
    ]
