# Generated by Django 2.2.12 on 2020-04-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location_page', '0001_initial'),
        ('base', '0001_initial'),
        ('service_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='related_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='service_page.ServicePage'),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='physical_location_photo',
            field=models.ForeignKey(blank=True, help_text='Use this to show an exterior of the location.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage', verbose_name='Choose a banner image'),
        ),
    ]
