# Generated by Django 2.2.14 on 2020-08-07 18:33

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('location_page', '0002_auto_20200410_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpage',
            name='hours_exceptions',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='hours_exceptions_ar',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='hours_exceptions_en',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='hours_exceptions_es',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='hours_exceptions_vi',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationpagerelatedservices',
            name='hours_exceptions',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='locationpagerelatedservices',
            name='hours_exceptions_ar',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationpagerelatedservices',
            name='hours_exceptions_en',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationpagerelatedservices',
            name='hours_exceptions_es',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='locationpagerelatedservices',
            name='hours_exceptions_vi',
            field=wagtail.core.fields.RichTextField(blank=True, max_length=255, null=True),
        ),
    ]
