# Generated by Django 2.2.12 on 2020-04-10 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('preview_janis_branch_for_pr', models.TextField(blank=True, help_text='Name of Janis branch to preview pages. Ex: "3000-my-issue-name" (Don\'t add quotes)', null=True, verbose_name='Preview Janis Branch Name')),
                ('publish_janis_branch_for_pr', models.TextField(blank=True, help_text='Name of Janis branch you want to publish to. Ex: "3000-my-issue-name" (Don\'t add quotes)', null=True, verbose_name='Publish Janis Branch Name')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
