# Generated by Django 2.2.11 on 2020-04-03 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_auto_20200326_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='preview_janis_branch',
            field=models.TextField(blank=True, help_text='Name of Janis branch to preview pages. Ex: "3000-my-issue-name" (Don\'t add quotes)', null=True, verbose_name='Preview Janis Branch Name'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='publish_janis_branch',
            field=models.TextField(blank=True, help_text='Name of Janis branch you want to publish to. Ex: "3000-my-issue-name" (Don\'t add quotes)', null=True, verbose_name='Publish Janis Branch Name'),
        ),
    ]
