# Generated by Django 2.2.11 on 2020-04-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_auto_20200403_1537'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='preview_janis_branch',
            new_name='preview_janis_branch_for_pr',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='publish_janis_branch',
            new_name='publish_janis_branch_for_pr',
        ),
    ]
