# Generated by Django 2.2.16 on 2020-10-02 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0003_homepagetoppage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepagetoppage',
            old_name='department',
            new_name='home_page',
        ),
    ]
