# Generated by Django 2.2.12 on 2020-04-10 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('topic_collection_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccollectionpage',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='topic_collection_pages', to='theme.Theme'),
        ),
    ]
