# Generated by Django 2.2.11 on 2020-03-26 23:44

import base.blocks
from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('service_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='dynamic_content',
            field=wagtail.core.fields.StreamField([('what_do_i_do_with_block', base.blocks.WhatDoIDoWithBlock()), ('collection_schedule_block', base.blocks.CollectionScheduleBlock()), ('recollect_block', base.blocks.RecollectBlock())], blank=True, verbose_name='Add any maps or apps that will help the resident use the service'),
        ),
    ]
