# Generated by Django 2.2.7 on 2019-11-19 22:26

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0097_formpage_formpagerelateddepartments_formpagetopic'),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('alternate_name', models.CharField(blank=True, max_length=255)),
                ('physical_street', models.TextField()),
                ('physical_city', models.CharField(default='Austin', max_length=255)),
                ('physical_state', models.CharField(default='TX', max_length=2)),
                ('physical_country', models.CharField(default='USA', max_length=100)),
                ('physical_zip', models.CharField(max_length=50)),
                ('mailing_street', models.TextField()),
                ('mailing_city', models.CharField(default='Austin', max_length=255)),
                ('mailing_state', models.CharField(default='TX', max_length=2)),
                ('mailing_country', models.CharField(default='USA', max_length=100)),
                ('mailing_zip', models.CharField(max_length=50)),
                ('nearest_bus_1', models.CharField(max_length=255)),
                ('nearest_bus_2', models.CharField(max_length=255)),
                ('nearest_bus_3', models.CharField(max_length=255)),
                ('physical_location_photo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LocationsIndexPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='LocationPageRelatedServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_services', to='locations.LocationPage')),
                ('related_service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.ServicePage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
