# Generated by Django 2.2.7 on 2019-11-19 00:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationPageRelatedMailingAddress',
            fields=[
                ('location_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.Location')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('locations.location', models.Model),
        ),
        migrations.CreateModel(
            name='LocationPageRelatedPhysicalAddress',
            fields=[
                ('physicaladdress_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='locations.PhysicalAddress')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('locations.physicaladdress', models.Model),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='mailing_address',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.LocationPageRelatedMailingAddress'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='physical_address',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='locations.LocationPageRelatedPhysicalAddress'),
        ),
        migrations.DeleteModel(
            name='LocationPageRelatedLocations',
        ),
        migrations.AddField(
            model_name='locationpagerelatedphysicaladdress',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_physical_address', to='locations.LocationPage'),
        ),
        migrations.AddField(
            model_name='locationpagerelatedmailingaddress',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_mailing_address', to='locations.LocationPage'),
        ),
    ]
