# Generated by Django 2.2.7 on 2019-12-02 18:35

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpage',
            name='alternate_name',
            field=models.CharField(blank=True, help_text='Use this field if the building has a second name, or is inside a larger facility', max_length=255, verbose_name='Location alternate name'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email address'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='mailing_city',
            field=models.CharField(blank=True, default='Austin', max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='mailing_state',
            field=models.CharField(blank=True, default='TX', max_length=255, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='mailing_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street or PO box'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='mailing_zip',
            field=models.CharField(blank=True, max_length=255, verbose_name='ZIP'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='phone_description',
            field=models.CharField(blank=True, max_length=255, verbose_name='Phone description'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None, verbose_name='Phone(only if location has a dedicated number)'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='physical_city',
            field=models.CharField(blank=True, default='Austin', max_length=255, verbose_name='City'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='physical_state',
            field=models.CharField(blank=True, default='TX', max_length=255, verbose_name='State'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='physical_street',
            field=models.CharField(blank=True, max_length=255, verbose_name='Street'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='physical_unit',
            field=models.CharField(blank=True, max_length=255, verbose_name='Floor/Suite #'),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='physical_zip',
            field=models.CharField(blank=True, max_length=255, verbose_name='ZIP'),
        ),
    ]
