# Generated by Django 2.2.7 on 2019-11-21 18:53

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='phone_description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None),
        ),
    ]
