# Generated by Django 2.2.7 on 2019-11-20 18:33

from django.db import migrations, models
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='author_notes',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Notes for authors (Not visible on the resident facing site)'),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='coa_global',
            field=models.BooleanField(default=False, verbose_name='Make this a top level page'),
        ),
        migrations.AddField(
            model_name='locationpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='locationpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
