# Generated by Django 2.2.7 on 2019-12-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20191205_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpage',
            name='nearest_bus_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='nearest_bus_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='locationpage',
            name='nearest_bus_3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
