# Generated by Django 2.2.7 on 2019-11-21 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0002_auto_20191121_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
