# Generated by Django 2.2.9 on 2020-01-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200108_2218'),
    ]

    operations = [
    ]
