# Generated by Django 2.2.9 on 2020-01-15 05:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200108_2218'),
        ('base', '0004_auto_20200115_0501')
    ]

    operations = [
    ]


'''
AUTOGENERATED MIGRATION


# Generated by Django 2.2.9 on 2020-01-15 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200115_0436'),
        ('locations', '0004_auto_20200108_2218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationpage',
            options={},
        ),
        migrations.RemoveField(
            model_name='locationpage',
            name='author_notes',
        ),
        migrations.RemoveField(
            model_name='locationpage',
            name='coa_global',
        ),
        migrations.RemoveField(
            model_name='locationpage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='locationpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='locationpage',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='locationpage',
            name='janisbasepage_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.JanisBasePage'),
            preserve_default=False,
        ),
    ]



'''