# Generated by Django 2.2.9 on 2020-01-29 02:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200108_2218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationpagerelatedservices',
            name='related_service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.ServicePage'),
        ),
    ]
