# Generated by Django 2.2.7 on 2019-11-21 19:48

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_formpage_formpagerelateddepartments_formpagetopic'),
        ('locations', '0004_locationoperatinghours'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationDayAndDuration',
            fields=[
                ('dayandduration_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.DayAndDuration')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('contact', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='locations.LocationPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
            bases=('base.dayandduration', models.Model),
        ),
        migrations.DeleteModel(
            name='LocationOperatingHours',
        ),
    ]
