# Generated by Django 2.2.9 on 2020-01-18 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200108_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='hours_same_as_location',
            field=models.BooleanField(default=False, verbose_name='The hours for this service are the same as the location hours'),
        ),
    ]
