# Generated by Django 2.2.9 on 2020-01-18 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_locationpagerelatedservices_hours_same_as_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='locationpagerelatedservices',
            options={'ordering': ['sort_order']},
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='sort_order',
            field=models.IntegerField(blank=True, editable=False, null=True),
        ),
    ]
