# Generated by Django 2.2.7 on 2019-11-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20191121_1948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='locationdayandduration',
            old_name='contact',
            new_name='page',
        ),
        migrations.AddField(
            model_name='locationdayandduration',
            name='exceptions',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
