# Generated by Django 2.2.7 on 2019-11-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20191121_1956'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationdayandduration',
            name='exceptions',
        ),
        migrations.AddField(
            model_name='locationpage',
            name='hours_exceptions',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
