# Generated by Django 2.2.7 on 2019-11-26 02:08

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20191121_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='exceptions',
            field=wagtail.core.fields.StreamField([('exceptions', wagtail.core.blocks.StructBlock([('open_or_closed', wagtail.core.blocks.ChoiceBlock(choices=[('open', 'Open'), ('closed', 'Closed')])), ('recurrence', wagtail.core.blocks.ChoiceBlock(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th')])), ('start_time', wagtail.core.blocks.TimeBlock()), ('start_time_AM', wagtail.core.blocks.ChoiceBlock(choices=[('am', 'A.M.'), ('pm', 'P.M')])), ('end_time', wagtail.core.blocks.TimeBlock()), ('end_time_AM', wagtail.core.blocks.ChoiceBlock(choices=[('am', 'A.M.'), ('pm', 'P.M')]))]))], blank=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='hours_by_day',
            field=wagtail.core.fields.StreamField([('hours', wagtail.core.blocks.StructBlock([('monday', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('open', wagtail.core.blocks.BooleanBlock()), ('start_time', wagtail.core.blocks.TimeBlock()), ('end_time', wagtail.core.blocks.TimeBlock())]))), ('tuesday', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('open', wagtail.core.blocks.BooleanBlock()), ('start_time', wagtail.core.blocks.TimeBlock()), ('end_time', wagtail.core.blocks.TimeBlock())]))), ('wednesday', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('open', wagtail.core.blocks.BooleanBlock()), ('start_time', wagtail.core.blocks.TimeBlock()), ('end_time', wagtail.core.blocks.TimeBlock())]))), ('thursday', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('open', wagtail.core.blocks.BooleanBlock()), ('start_time', wagtail.core.blocks.TimeBlock()), ('end_time', wagtail.core.blocks.TimeBlock())]))), ('friday', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('open', wagtail.core.blocks.BooleanBlock()), ('start_time', wagtail.core.blocks.TimeBlock()), ('end_time', wagtail.core.blocks.TimeBlock())]))), ('saturday', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('open', wagtail.core.blocks.BooleanBlock()), ('start_time', wagtail.core.blocks.TimeBlock()), ('end_time', wagtail.core.blocks.TimeBlock())]))), ('sunday', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('open', wagtail.core.blocks.BooleanBlock()), ('start_time', wagtail.core.blocks.TimeBlock()), ('end_time', wagtail.core.blocks.TimeBlock())])))]))], blank=True),
        ),
    ]
