# Generated by Django 2.2.7 on 2019-11-25 21:01

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20191121_2000'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='hours_exceptions',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='hours_list',
            field=wagtail.core.fields.StreamField([('hours', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('day', wagtail.core.blocks.ChoiceBlock(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')])), ('start_time', wagtail.core.blocks.TimeBlock()), ('end_time', wagtail.core.blocks.TimeBlock())])))], blank=True),
        ),
    ]
