# Generated by Django 2.2.10 on 2020-03-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20200118_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='hours_exceptions_ar',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='hours_exceptions_en',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='hours_exceptions_es',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='hours_exceptions_vi',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
