# Generated by Django 2.2.7 on 2019-11-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20191126_0208'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='monday_duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='monday_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
