# Generated by Django 2.2.7 on 2019-11-26 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0009_auto_20191126_1716'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationpagerelatedservices',
            name='monday_duration',
        ),
        migrations.RemoveField(
            model_name='locationpagerelatedservices',
            name='monday_time',
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='friday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='friday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='monday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='monday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='saturday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='saturday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='sunday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='sunday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='thursday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='thursday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='tuesday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='tuesday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='wednesday_end_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='wednesday_start_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
