# Generated by Django 2.2.7 on 2019-11-26 20:03

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0012_auto_20191126_1750'),
    ]

    operations = [
        migrations.CreateModel(
            name='StartTimeEndTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_range', to='locations.LocationPageRelatedServices')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
