# Generated by Django 2.2.6 on 2019-11-26 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0013_starttimeendtime'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StartTimeEndTime',
        ),
    ]
