# Generated by Django 2.2.7 on 2019-11-26 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0014_delete_starttimeendtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpagerelatedservices',
            name='hours_exceptions',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
