# Generated by Django 2.2.6 on 2019-11-26 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0018_auto_20191126_2141'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationpage',
            name='hours_exceptions',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
