# Generated by Django 2.2.12 on 2020-05-08 12:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newspage',
            name='written_for_department',
            field=models.ForeignKey(blank=True, help_text="If this news is written for another department, select that department below. This ensures that this news is associated with that department's news content", null=True, on_delete=django.db.models.deletion.SET_NULL, to='department_page.DepartmentPage', verbose_name='Assign a different department'),
        ),
    ]
