# Generated by Django 2.2.11 on 2020-04-06 07:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_auto_20200326_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPhoneNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('phone_description', models.CharField(blank=True, max_length=255)),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='hours_exceptions',
        ),
        migrations.DeleteModel(
            name='ContactDayAndDuration',
        ),
        migrations.DeleteModel(
            name='DayAndDuration',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
        migrations.AddField(
            model_name='contactphonenumber',
            name='contact',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='contact.Contact'),
        ),
    ]
