# Generated by Django 2.2.11 on 2020-03-26 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0001_initial'),
        ('topic_collection_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedimage',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user'),
        ),
        migrations.AddField(
            model_name='topiccollectionpagetopiccollection',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topiccollections', to='topic_collection_page.TopicCollectionPage'),
        ),
        migrations.AddField(
            model_name='topiccollectionpagetopiccollection',
            name='topiccollection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='topic_collection_page.TopicCollectionPage', verbose_name='Select a Topic Collection'),
        ),
        migrations.AddField(
            model_name='janisbranchsettings',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site'),
        ),
        migrations.AlterUniqueTogether(
            name='translatedimagerendition',
            unique_together={('image', 'filter_spec', 'focal_point_key')},
        ),
    ]
