# Generated by Django 2.2.10 on 2020-03-11 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('location_page', '0002_auto_20200311_1558'),
        ('topic_collection_page', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedimage',
            name='uploaded_by_user',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='uploaded by user'),
        ),
        migrations.AddField(
            model_name='topiccollectionpagetopiccollection',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topiccollections', to='topic_collection_page.TopicCollectionPage'),
        ),
        migrations.AddField(
            model_name='topiccollectionpagetopiccollection',
            name='topiccollection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='topic_collection_page.TopicCollectionPage', verbose_name='Select a Topic Collection'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='contact',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='base.Contact'),
        ),
        migrations.AddField(
            model_name='map',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Location'),
        ),
        migrations.AddField(
            model_name='janisbranchsettings',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site'),
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.Location'),
        ),
        migrations.AddField(
            model_name='contact',
            name='location_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='location_page.LocationPage', verbose_name='Select a Location'),
        ),
        migrations.AlterUniqueTogether(
            name='translatedimagerendition',
            unique_together={('image', 'filter_spec', 'focal_point_key')},
        ),
        migrations.AddField(
            model_name='contactdayandduration',
            name='contact',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='base.Contact'),
        ),
    ]
