# Generated by Django 2.2.10 on 2020-03-06 11:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0045_assign_unlock_grouppagepermission'),
        ('topic_collection_page', '0001_initial'),
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='topiccollectionpagetopiccollection',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topiccollections', to='topic_collection_page.TopicCollectionPage'),
        ),
        migrations.AddField(
            model_name='topiccollectionpagetopiccollection',
            name='topiccollection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='topic_collection_page.TopicCollectionPage', verbose_name='Select a Topic Collection'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='contact',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_number', to='base.Contact'),
        ),
        migrations.AddField(
            model_name='map',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Location'),
        ),
        migrations.AddField(
            model_name='janisbranchsettings',
            name='site',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage'),
        ),
        migrations.AddField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.Location'),
        ),
    ]
