# Generated by Django 2.2.11 on 2020-04-04 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200326_1045'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JanisBranchSettings',
        ),
    ]
