# Generated by Django 2.2.9 on 2020-01-07 23:05

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0003_auto_20191206_0602'),
        ('base', '0002_auto_20200107_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.LocationPage', verbose_name='Select a Location'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps',
            field=wagtail.core.fields.StreamField([('basic_step', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Basic Step')), ('step_with_options_accordian', wagtail.core.blocks.StructBlock([('options_description', wagtail.core.blocks.RichTextBlock(classname='coa-option-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('option_name', wagtail.core.blocks.TextBlock(label='Option name. (When clicked, this name will expand the content for this option')), ('option_description', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Option Content'))])))], label='Step With Options')), ('step_with_locations', wagtail.core.blocks.StructBlock([('locations_description', wagtail.core.blocks.RichTextBlock(classname='coa-locations-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('locations', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(label='Location', page_type=['locations.LocationPage'])))], label='Step with locations'))], blank=True, help_text='A step may have a basic text step or an options accordion which reveals two or more options', verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps_ar',
            field=wagtail.core.fields.StreamField([('basic_step', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Basic Step')), ('step_with_options_accordian', wagtail.core.blocks.StructBlock([('options_description', wagtail.core.blocks.RichTextBlock(classname='coa-option-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('option_name', wagtail.core.blocks.TextBlock(label='Option name. (When clicked, this name will expand the content for this option')), ('option_description', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Option Content'))])))], label='Step With Options')), ('step_with_locations', wagtail.core.blocks.StructBlock([('locations_description', wagtail.core.blocks.RichTextBlock(classname='coa-locations-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('locations', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(label='Location', page_type=['locations.LocationPage'])))], label='Step with locations'))], blank=True, help_text='A step may have a basic text step or an options accordion which reveals two or more options', null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps_en',
            field=wagtail.core.fields.StreamField([('basic_step', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Basic Step')), ('step_with_options_accordian', wagtail.core.blocks.StructBlock([('options_description', wagtail.core.blocks.RichTextBlock(classname='coa-option-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('option_name', wagtail.core.blocks.TextBlock(label='Option name. (When clicked, this name will expand the content for this option')), ('option_description', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Option Content'))])))], label='Step With Options')), ('step_with_locations', wagtail.core.blocks.StructBlock([('locations_description', wagtail.core.blocks.RichTextBlock(classname='coa-locations-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('locations', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(label='Location', page_type=['locations.LocationPage'])))], label='Step with locations'))], blank=True, help_text='A step may have a basic text step or an options accordion which reveals two or more options', null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps_es',
            field=wagtail.core.fields.StreamField([('basic_step', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Basic Step')), ('step_with_options_accordian', wagtail.core.blocks.StructBlock([('options_description', wagtail.core.blocks.RichTextBlock(classname='coa-option-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('option_name', wagtail.core.blocks.TextBlock(label='Option name. (When clicked, this name will expand the content for this option')), ('option_description', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Option Content'))])))], label='Step With Options')), ('step_with_locations', wagtail.core.blocks.StructBlock([('locations_description', wagtail.core.blocks.RichTextBlock(classname='coa-locations-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('locations', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(label='Location', page_type=['locations.LocationPage'])))], label='Step with locations'))], blank=True, help_text='A step may have a basic text step or an options accordion which reveals two or more options', null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps_vi',
            field=wagtail.core.fields.StreamField([('basic_step', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Basic Step')), ('step_with_options_accordian', wagtail.core.blocks.StructBlock([('options_description', wagtail.core.blocks.RichTextBlock(classname='coa-option-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('option_name', wagtail.core.blocks.TextBlock(label='Option name. (When clicked, this name will expand the content for this option')), ('option_description', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Option Content'))])))], label='Step With Options')), ('step_with_locations', wagtail.core.blocks.StructBlock([('locations_description', wagtail.core.blocks.RichTextBlock(classname='coa-locations-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('locations', wagtail.core.blocks.ListBlock(wagtail.core.blocks.PageChooserBlock(label='Location', page_type=['locations.LocationPage'])))], label='Step with locations'))], blank=True, help_text='A step may have a basic text step or an options accordion which reveals two or more options', null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
    ]
