# Generated by Django 2.2.10 on 2020-03-06 11:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0002_auto_20200306_1141'),
        ('location_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='location_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='location_page.LocationPage', verbose_name='Select a Location'),
        ),
        migrations.AlterUniqueTogether(
            name='translatedimagerendition',
            unique_together={('image', 'filter_spec', 'focal_point_key')},
        ),
        migrations.AddField(
            model_name='contactdayandduration',
            name='contact',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='hours', to='base.Contact'),
        ),
    ]
