# Generated by Django 2.2.11 on 2020-03-26 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20200312_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='location',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='location_page',
        ),
        migrations.RemoveField(
            model_name='contactdayandduration',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='contactdayandduration',
            name='dayandduration_ptr',
        ),
        migrations.DeleteModel(
            name='Location',
        ),
        migrations.RemoveField(
            model_name='map',
            name='location',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='contact',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.DeleteModel(
            name='ContactDayAndDuration',
        ),
        migrations.DeleteModel(
            name='DayAndDuration',
        ),
        migrations.DeleteModel(
            name='Map',
        ),
        migrations.DeleteModel(
            name='PhoneNumber',
        ),
    ]
