# Generated by Django 2.2.12 on 2020-04-10 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('topic_collection_page', '0002_auto_20200410_0954'),
        ('base', '0003_delete_janisbranchsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
    ]
