# Generated by Django 2.2.9 on 2020-01-16 00:44

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20200108_2218'),
        ('base', '0003_auto_20200107_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='JanisUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=9001)),
                ('language', models.CharField(max_length=9)),
                ('department_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.DepartmentPage')),
                ('form_container', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.FormContainer')),
                ('guide_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.GuidePage')),
                ('information_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.InformationPage')),
                ('location_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.LocationPage')),
                ('official_documents_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.OfficialDocumentPage')),
                ('service_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.ServicePage')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Theme')),
                ('topic_collection_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TopicCollectionPage')),
                ('topic_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TopicPage')),
            ],
        ),
        migrations.CreateModel(
            name='TopicPageJanisUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janis_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.JanisUrl', verbose_name='URL')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='janis_urls', to='base.TopicPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
