# Generated by Django 2.2.8 on 2020-01-22 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200107_2305'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='informationpage',
            options={},
        ),
        migrations.AlterModelTable(
            name='informationpage',
            table='base_informationpage',
        ),
        migrations.AlterModelTable(
            name='informationpagecontact',
            table='base_informationpagecontact',
        ),
        migrations.AlterModelTable(
            name='informationpagerelateddepartments',
            table='base_informationpagerelateddepartments',
        ),
        migrations.AlterModelTable(
            name='informationpagetopic',
            table='base_informationpagetopic',
        ),
    ]
