# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-07 16:03
from __future__ import unicode_literals

import base.blocks
from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20171206_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='content_en',
            field=wagtail.wagtailcore.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='content_es',
            field=wagtail.wagtailcore.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='content_fr',
            field=wagtail.wagtailcore.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='content_pt',
            field=wagtail.wagtailcore.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='extra_content',
            field=wagtail.wagtailcore.fields.StreamField((('content', wagtail.wagtailcore.blocks.RichTextBlock(features=['h1', 'h2', 'link', 'ul', 'ol'], help_text='Write any additional content describing the service')), ('application_block', base.blocks.SnippetChooserBlockWithAPIGoodness('base.ApplicationBlock'))), verbose_name='Add any forms, maps, apps, or content that will help the resident use the service'),
        ),
    ]
