# Generated by Django 2.2.12 on 2020-04-10 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_delete_janisbranchsettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theme',
        ),
        migrations.DeleteModel(
            name='TopicCollectionPageTopicCollection',
        ),
    ]
