# Generated by Django 2.2.9 on 2020-01-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200107_2305'),
    ]

    operations = [
    ]

'''
AUTOGENERATED MIGRATION

# Generated by Django 2.2.9 on 2020-01-15 04:36

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('base', '0003_auto_20200107_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='JanisBasePage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_notes', wagtail.core.fields.RichTextField(blank=True, verbose_name='Notes for authors (Not visible on the resident facing site)')),
                ('coa_global', models.BooleanField(default=False, verbose_name='Make this a top level page')),
            ],
            options={
                'permissions': [('view_extra_panels', 'Can view extra panels'), ('view_snippets', 'Can view snippets'), ('add_snippets', 'Can add snippet'), ('delete_snippets', 'Can delete snippet')],
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterModelOptions(
            name='departmentpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='formcontainer',
            options={},
        ),
        migrations.AlterModelOptions(
            name='guidepage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='informationpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='officialdocumentpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='processpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='servicepage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topiccollectionpage',
            options={},
        ),
        migrations.AlterModelOptions(
            name='topicpage',
            options={},
        ),
        migrations.RemoveField(
            model_name='departmentpage',
            name='author_notes',
        ),
        migrations.RemoveField(
            model_name='departmentpage',
            name='coa_global',
        ),
        migrations.RemoveField(
            model_name='departmentpage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='departmentpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='departmentpage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='formcontainer',
            name='author_notes',
        ),
        migrations.RemoveField(
            model_name='formcontainer',
            name='coa_global',
        ),
        migrations.RemoveField(
            model_name='formcontainer',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='formcontainer',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='formcontainer',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='guidepage',
            name='author_notes',
        ),
        migrations.RemoveField(
            model_name='guidepage',
            name='coa_global',
        ),
        migrations.RemoveField(
            model_name='guidepage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='guidepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='guidepage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='informationpage',
            name='author_notes',
        ),
        migrations.RemoveField(
            model_name='informationpage',
            name='coa_global',
        ),
        migrations.RemoveField(
            model_name='informationpage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='informationpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='informationpage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='officialdocumentpage',
            name='author_notes',
        ),
        migrations.RemoveField(
            model_name='officialdocumentpage',
            name='coa_global',
        ),
        migrations.RemoveField(
            model_name='officialdocumentpage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='officialdocumentpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='officialdocumentpage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='author_notes',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='coa_global',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='author_notes',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='coa_global',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='topiccollectionpage',
            name='author_notes',
        ),
        migrations.RemoveField(
            model_name='topiccollectionpage',
            name='coa_global',
        ),
        migrations.RemoveField(
            model_name='topiccollectionpage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topiccollectionpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='topiccollectionpage',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='author_notes',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='coa_global',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='updated_at',
        ),
        migrations.CreateModel(
            name='JanisUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=9001)),
                ('language', models.CharField(max_length=9)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.DepartmentPage')),
                ('page', modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='janis_urls', to='base.JanisBasePage')),
                ('theme', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Theme')),
                ('topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.TopicPage')),
                ('topic_collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.TopicCollectionPage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='departmentpage',
            name='janisbasepage_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.JanisBasePage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formcontainer',
            name='janisbasepage_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.JanisBasePage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guidepage',
            name='janisbasepage_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.JanisBasePage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='informationpage',
            name='janisbasepage_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.JanisBasePage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='officialdocumentpage',
            name='janisbasepage_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.JanisBasePage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='processpage',
            name='janisbasepage_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.JanisBasePage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicepage',
            name='janisbasepage_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.JanisBasePage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topiccollectionpage',
            name='janisbasepage_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.JanisBasePage'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topicpage',
            name='janisbasepage_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.JanisBasePage'),
            preserve_default=False,
        ),
    ]





'''