# Generated by Django 2.2.9 on 2020-01-15 05:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200107_2305'),
    ]

    operations = [
    ]
