# Generated by Django 2.2.9 on 2020-01-22 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200122_1859'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='informationpage',
            table='informations_informationpage',
        ),
        migrations.AlterModelTable(
            name='informationpagecontact',
            table='informations_informationpagecontact',
        ),
        migrations.AlterModelTable(
            name='informationpagerelateddepartments',
            table='informations_informationpagerelateddepartments',
        ),
        migrations.AlterModelTable(
            name='informationpagetopic',
            table='informations_informationpagetopic',
        ),
    ]
