# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-04 20:48
from __future__ import unicode_literals

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20171228_1924'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='content_fr',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='content_pt',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='content_ar',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='content_ko',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='content_my',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='content_ur',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='content_vi',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='content_zh_hans',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='content_zh_hant',
            field=wagtail.core.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
    ]
