# Generated by Django 2.2.9 on 2020-01-16 04:43

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_janisurl_topicpagejanisurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCollectionPageJanisUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janis_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.JanisUrl', verbose_name='URL')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='janis_urls', to='base.TopicCollectionPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
