# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-01-05 05:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20180104_2048'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='description',
            field=models.TextField(default='This is a bunch of text to describe this very important topic. Please enjoy it with friends.'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='base.Topic'),
        ),
    ]
