# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 01:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20180105_0538'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='actionable_title',
            field=models.CharField(default='DEFAULT ACT. TITLE', max_length=255, verbose_name='Actionable Title'),
        ),
    ]
