# Generated by Django 2.2.9 on 2020-02-12 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200210_1640'),
        ('base', '0006_auto_20200211_1137'),
    ]

    operations = [
    ]
