# Generated by Django 2.2.10 on 2020-03-03 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20200118_0044'),
        ('base', '0007_merge_20200212_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='location_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='locations.LocationPage', verbose_name='Select a Location'),
        ),
    ]
