# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-12 01:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_servicepage_actionable_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='actionable_title',
        ),
    ]
