# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 22:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0019_delete_filter'),
        ('base', '0007_department_departmentcontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image'),
        ),
    ]
