# Generated by Django 2.2.9 on 2020-01-16 07:25

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_locationpagejanisurl'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePageJanisUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janis_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.JanisUrl', verbose_name='URL')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='janis_urls', to='base.ServicePage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficialDocumentPageJanisUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janis_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.JanisUrl', verbose_name='URL')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='janis_urls', to='base.OfficialDocumentPage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformationPageJanisUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janis_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.JanisUrl', verbose_name='URL')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='janis_urls', to='base.InformationPage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GuidePageJanisUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janis_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.JanisUrl', verbose_name='URL')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='janis_urls', to='base.GuidePage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormContainerJanisUrl',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('janis_url', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.JanisUrl', verbose_name='URL')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='janis_urls', to='base.FormContainer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
