# Generated by Django 2.2.10 on 2020-03-05 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_merge_20200212_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpage',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.Contact'),
        ),
        migrations.AddField(
            model_name='guidepage',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.Contact'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.Contact'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.Contact'),
        ),
    ]
