# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 01:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_auto_20180118_0144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='feed_image',
        ),
    ]
