# Generated by Django 2.2.10 on 2020-03-13 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('base', '0008_auto_20200313_1917'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdocumentpageofficialdocument',
            name='document_es',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document'),
        ),
    ]
