# Generated by Django 2.2.10 on 2020-03-21 02:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_officialdocumentpageofficialdocument_document_es'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialdocumentpageofficialdocument',
            name='document',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Document [en]'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpageofficialdocument',
            name='document_es',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtaildocs.Document', verbose_name='Document [es]'),
        ),
    ]
