# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-16 02:29
from __future__ import unicode_literals

import base.blocks
from django.db import migrations, models
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_auto_20180123_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='additional_content',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.RenameField(
            model_name='servicepage',
            old_name='content',
            new_name='steps',
        ),
        migrations.RenameField(
            model_name='servicepage',
            old_name='content_en',
            new_name='steps_en',
        ),
        migrations.RenameField(
            model_name='servicepage',
            old_name='content_es',
            new_name='steps_es',
        ),
        migrations.RenameField(
            model_name='servicepage',
            old_name='content_vi',
            new_name='steps_vi',
        ),
        migrations.RenameField(
            model_name='servicepage',
            old_name='content_ar',
            new_name='steps_ar',
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='extra_content',
            field=wagtail.core.fields.StreamField((('map_block', base.blocks.SnippetChooserBlockWithAPIGoodness('base.Map', icon='site')), ('what_do_i_do_with_block', base.blocks.WhatDoIDoWithBlock()), ('collection_schedule_block', base.blocks.CollectionScheduleBlock())), verbose_name='Add any forms, maps, apps, or content that will help the resident use the service'),
        ),
        migrations.RenameField(
            model_name='servicepage',
            old_name='extra_content',
            new_name='dynamic_content',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='content_ko',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='content_my',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='content_ur',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='content_zh_hans',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='content_zh_hant',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='title_ar',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='title_en',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='title_es',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='title_vi',
            field=models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='additional_content_ar',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='additional_content_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='additional_content_es',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='additional_content_vi',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='description_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='slug',
            field=models.SlugField(default='topic'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='topic',
            name='text_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='text_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='text_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='topic',
            name='text_vi',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
