# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-17 02:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_auto_20180316_2253'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplicationBlock',
        ),
    ]
