# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-21 01:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_delete_applicationblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='mission_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='mission_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='mission_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='mission_vi',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='name_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='slug',
            field=models.SlugField(default='slug'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage'),
        ),
    ]
