# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-23 22:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20180321_0132'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='map',
            name='description_vi',
            field=models.TextField(null=True),
        ),
    ]
