# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_auto_20180326_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('text', models.CharField(max_length=255)),
                ('text_ar', models.CharField(max_length=255, null=True)),
                ('text_en', models.CharField(max_length=255, null=True)),
                ('text_es', models.CharField(max_length=255, null=True)),
                ('text_vi', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('description_vi', models.TextField(null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
