# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2018-03-26 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='topic',
            name='theme',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='base.Theme'),
            preserve_default=False,
        ),
    ]
