# Generated by Django 2.0.6 on 2018-06-07 18:15

import base.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('base', '0020_threeoneone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_ar', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_es', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_vi', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('steps', wagtail.core.fields.RichTextField(verbose_name='Write out the steps a resident needs to take to use the service')),
                ('steps_ar', wagtail.core.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service')),
                ('steps_en', wagtail.core.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service')),
                ('steps_es', wagtail.core.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service')),
                ('steps_vi', wagtail.core.fields.RichTextField(null=True, verbose_name='Write out the steps a resident needs to take to use the service')),
                ('dynamic_content', wagtail.core.fields.StreamField((('map_block', base.blocks.SnippetChooserBlockWithAPIGoodness('base.Map', icon='site')), ('what_do_i_do_with_block', base.blocks.WhatDoIDoWithBlock()), ('collection_schedule_block', base.blocks.CollectionScheduleBlock()), ('recollect_block', base.blocks.RecollectBlock())), verbose_name='Add any forms, maps, apps, or content that will help the resident use the service')),
                ('additional_content', wagtail.core.fields.RichTextField(blank=True, verbose_name='Write any additional content describing the service')),
                ('additional_content_ar', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service')),
                ('additional_content_en', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service')),
                ('additional_content_es', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service')),
                ('additional_content_vi', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='base.Topic')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.Location'),
        ),
        migrations.AlterField(
            model_name='translatedimagerendition',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renditions', to='base.TranslatedImage'),
        ),
    ]
