# Generated by Django 2.0.5 on 2018-06-15 21:18

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('base', '0020_threeoneone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('title_ar', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_en', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_es', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('title_vi', models.CharField(help_text="The page title as you'd like it to be seen by the public", max_length=255, null=True, verbose_name='title')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_vi', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='processes', to='base.Topic')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='ProcessPageStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=75)),
                ('title_ar', models.CharField(max_length=75, null=True)),
                ('title_en', models.CharField(max_length=75, null=True)),
                ('title_es', models.CharField(max_length=75, null=True)),
                ('title_vi', models.CharField(max_length=75, null=True)),
                ('short_title', models.CharField(max_length=25)),
                ('short_title_ar', models.CharField(max_length=25, null=True)),
                ('short_title_en', models.CharField(max_length=25, null=True)),
                ('short_title_es', models.CharField(max_length=25, null=True)),
                ('short_title_vi', models.CharField(max_length=25, null=True)),
                ('link_title', models.CharField(max_length=25)),
                ('link_title_ar', models.CharField(max_length=25, null=True)),
                ('link_title_en', models.CharField(max_length=25, null=True)),
                ('link_title_es', models.CharField(max_length=25, null=True)),
                ('link_title_vi', models.CharField(max_length=25, null=True)),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_vi', models.TextField(blank=True, null=True)),
                ('overview_steps', wagtail.core.fields.RichTextField(blank=True, verbose_name='Write out the steps a resident needs to take to use the service')),
                ('overview_steps_ar', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write out the steps a resident needs to take to use the service')),
                ('overview_steps_en', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write out the steps a resident needs to take to use the service')),
                ('overview_steps_es', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write out the steps a resident needs to take to use the service')),
                ('overview_steps_vi', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write out the steps a resident needs to take to use the service')),
                ('detailed_content', wagtail.core.fields.RichTextField(blank=True, verbose_name='Write any detailed content describing the process')),
                ('detailed_content_ar', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any detailed content describing the process')),
                ('detailed_content_en', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any detailed content describing the process')),
                ('detailed_content_es', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any detailed content describing the process')),
                ('detailed_content_vi', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any detailed content describing the process')),
                ('quote', models.TextField(blank=True)),
                ('quote_ar', models.TextField(blank=True, null=True)),
                ('quote_en', models.TextField(blank=True, null=True)),
                ('quote_es', models.TextField(blank=True, null=True)),
                ('quote_vi', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='base.ProcessPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='contact',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.Location'),
        ),
        migrations.AlterField(
            model_name='translatedimagerendition',
            name='image',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='renditions', to='base.TranslatedImage'),
        ),
    ]
