# Generated by Django 2.0.6 on 2018-06-28 07:01

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20180615_2118'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessPageContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Contact')),
                ('process', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='base.ProcessPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
