# Generated by Django 2.0.6 on 2018-06-28 16:36

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20180615_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processpagestep',
            name='link_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='processpagestep',
            name='link_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processpagestep',
            name='link_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processpagestep',
            name='link_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processpagestep',
            name='link_title_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processpagestep',
            name='short_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='processpagestep',
            name='short_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processpagestep',
            name='short_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processpagestep',
            name='short_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processpagestep',
            name='short_title_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processpagestep',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='processpagestep',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processpagestep',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processpagestep',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='processpagestep',
            name='title_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps_ar',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps_es',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps_vi',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
    ]
