# Generated by Django 2.0.6 on 2018-06-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_auto_20180607_1815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processpage',
            name='additional_content',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='additional_content_ar',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='additional_content_en',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='additional_content_es',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='additional_content_vi',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='dynamic_content',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='steps_ar',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='steps_en',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='steps_es',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='steps_vi',
        ),
        migrations.AddField(
            model_name='processpage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='processpage',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processpage',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processpage',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='processpage',
            name='description_vi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
