# Generated by Django 2.0.5 on 2018-06-14 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20180614_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processpage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='processpage',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processpage',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processpage',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processpage',
            name='description_vi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
