# Generated by Django 2.0.6 on 2018-06-07 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0022_auto_20180607_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processpage',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='processpage',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='processpage',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='processpage',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='processpage',
            name='description_vi',
            field=models.TextField(null=True),
        ),
    ]
