# Generated by Django 2.0.7 on 2018-08-02 16:52

import base.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0023_processpagecontact'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='dynamic_content',
            field=wagtail.core.fields.StreamField([('map_block', base.blocks.SnippetChooserBlockWithAPIGoodness('base.Map', icon='site')), ('what_do_i_do_with_block', base.blocks.WhatDoIDoWithBlock()), ('collection_schedule_block', base.blocks.CollectionScheduleBlock()), ('recollect_block', base.blocks.RecollectBlock())], verbose_name='Add any maps or apps that will help the resident use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage', verbose_name='Choose an image for the service banner'),
        ),
    ]
