# Generated by Django 2.0.8 on 2018-08-09 18:10

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_auto_20180801_2204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Write any additional content describing the service', verbose_name='Additional content'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_ar',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Write any additional content describing the service', null=True, verbose_name='Additional content'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_en',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Write any additional content describing the service', null=True, verbose_name='Additional content'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Write any additional content describing the service', null=True, verbose_name='Additional content'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_vi',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Write any additional content describing the service', null=True, verbose_name='Additional content'),
        ),
    ]
