# Generated by Django 2.0.8 on 2018-08-17 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0025_auto_20180816_0603'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='steps',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='steps_ar',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='steps_en',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='steps_es',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='steps_vi',
        ),
    ]
