# Generated by Django 2.0.8 on 2018-08-22 02:44

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0026_auto_20180817_1107'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepagestep',
            name='step_description_ar',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Step description'),
        ),
        migrations.AddField(
            model_name='servicepagestep',
            name='step_description_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Step description'),
        ),
        migrations.AddField(
            model_name='servicepagestep',
            name='step_description_es',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Step description'),
        ),
        migrations.AddField(
            model_name='servicepagestep',
            name='step_description_vi',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Step description'),
        ),
    ]
