# Generated by Django 2.0.8 on 2018-08-27 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0027_auto_20180822_0244'),
        ('base', '0025_auto_20180809_1810'),
    ]

    operations = [
    ]
