# Generated by Django 2.0.8 on 2018-09-19 03:55

import base.blocks
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0028_merge_20180827_2354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?', verbose_name='Write any additional content describing the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_ar',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?', null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_en',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?', null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?', null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_vi',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?', null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='dynamic_content',
            field=wagtail.core.fields.StreamField([('map_block', base.blocks.SnippetChooserBlockWithAPIGoodness('base.Map', icon='site')), ('what_do_i_do_with_block', base.blocks.WhatDoIDoWithBlock()), ('collection_schedule_block', base.blocks.CollectionScheduleBlock()), ('recollect_block', base.blocks.RecollectBlock())], blank=True, verbose_name='Add any maps or apps that will help the resident use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='base.Topic', verbose_name='Select a Topic'),
        ),
    ]
