# Generated by Django 2.0.8 on 2018-09-21 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0029_auto_20180919_0355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processpage',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage'),
        ),
    ]
