# Generated by Django 2.0.8 on 2018-09-25 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0030_auto_20180924_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processpage',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Topic', verbose_name='Select a Topic'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.Topic', verbose_name='Select a Topic'),
        ),
    ]
