# Generated by Django 2.0.8 on 2018-09-25 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0031_auto_20180925_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepagestep',
            name='page',
        ),
        migrations.DeleteModel(
            name='ServicePageStep',
        ),
    ]
