# Generated by Django 2.0.8 on 2018-09-27 05:00

from django.db import migrations
from pprint import pprint
from wagtail.core.blocks.stream_block import StreamValue

def better_steps(apps, schema_editor):
    '''
    We can't import the ServicePage model directly as it may be a newer
    version than this migration expects. We use the historical version.
    '''

# StreamValue.StreamChild(
#                 id=None,
#                 block=AccordionItemBlock(),
#                 value={
#                         'title': 'Title goes here',
#                         'text': RichText('Testing!'),
#                 }
#             )

    ServicePage = apps.get_model('base', 'ServicePage')
    ServicePageStep = apps.get_model('base', 'ServicePageStep')

    for page in ServicePage.objects.all():
      pageSteps = []
      for step in ServicePageStep.objects.all():
        if step.page_id == page.id:
          streamStep = {
            'type': 'basic_step',
            'value': step.step_description
          }
          pageSteps.append(streamStep)
      stream_block = page.steps.stream_block
      page.steps = StreamValue(stream_block, pageSteps, is_lazy=True)
      page.save()

    # page = ServicePage.objects.get(pk=13)
    # pprint(vars(page.steps))
    # for sstep in page.steps:
    #   pprint(vars(sstep))

    
    # for step in ServicePageStep.objects.all():
    #     # print(page.service_steps)
    #     if step.page_id == 13:
    #       pprint(vars(step))
        # for step in page.service_steps:
        #   print(step)

        # post.slug = slugify(post.title)
        # post.save()
    raise Exception('I know Python!')

class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_servicepage_steps'),
    ]

    operations = [
        migrations.RunPython(better_steps),
    ]
