# Generated by Django 2.0.8 on 2018-09-27 05:00

from django.db import migrations
from pprint import pprint
from wagtail.core.blocks.stream_block import StreamValue


def better_steps(apps, schema_editor):
    '''
    We can't import the models directly as they may be a newer
    version than this migration expects. We use the historical versions.
    '''
    ServicePage = apps.get_model('base', 'ServicePage')
    ServicePageStep = apps.get_model('base', 'ServicePageStep')

    for page in ServicePage.objects.all():
        pageSteps = []
        for step in ServicePageStep.objects.all():
            if step.page_id == page.id:
                streamStep = {
                    'type': 'basic_step',
                    'value': step.step_description
                }
                pageSteps.append(streamStep)
        stream_block = page.steps.stream_block
        page.steps = StreamValue(stream_block, pageSteps, is_lazy=True)
        page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0032_servicepage_steps'),
    ]

    operations = [
        migrations.RunPython(better_steps),
    ]
