# Generated by Django 2.0.9 on 2018-10-04 04:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0034_auto_20180927_0731'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processpagestep',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage'),
        ),
    ]
