# Generated by Django 2.0.10 on 2019-02-07 02:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('base', '0036_informationpage_informationpagecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('what_we_do', models.TextField(help_text='Use service-oriented language and a conversational tone. Try to stay away from jargon and just listing out services.', verbose_name='What we do')),
                ('mission', models.TextField(verbose_name='Mission')),
                ('directors', wagtail.core.fields.StreamField([('director', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('name', wagtail.core.blocks.TextBlock(label="Director's name")), ('photo', wagtail.images.blocks.ImageChooserBlock(label='Photo of the director')), ('about', wagtail.core.blocks.TextBlock(label='About the director')), ('email', wagtail.core.blocks.TextBlock(blank=True, label="Director's email")), ('phone', wagtail.core.blocks.TextBlock(blank=True, label="Director's phone"))])))], blank=True, verbose_name='Add directors.')),
                ('social_media', wagtail.core.fields.StreamField([('url', wagtail.core.blocks.URLBlock(label='Social media url'))], blank=True, verbose_name='Add social media urls.')),
                ('job_listings', models.URLField(blank=True, help_text='Link to a page with job listings.', verbose_name='Job listings url')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='DepartmentPageContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Contact')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='base.DepartmentPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
