# Generated by Django 2.0.10 on 2019-02-07 07:00

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0037_departmentpage_departmentpagecontact'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepartmentPageDirector',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('name', models.CharField(max_length=255)),
                ('about', models.TextField(blank=True)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='departmentpage',
            name='directors',
        ),
        migrations.AddField(
            model_name='departmentpagedirector',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_directors', to='base.DepartmentPage'),
        ),
        migrations.AddField(
            model_name='departmentpagedirector',
            name='photo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage'),
        ),
    ]
