# Generated by Django 2.0.13 on 2019-02-14 14:58

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0038_auto_20190207_0700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processpage',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='title_vi',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='title_vi',
        ),
        migrations.AddField(
            model_name='departmentpage',
            name='mission_ar',
            field=models.TextField(null=True, verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='departmentpage',
            name='mission_en',
            field=models.TextField(null=True, verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='departmentpage',
            name='mission_es',
            field=models.TextField(null=True, verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='departmentpage',
            name='mission_vi',
            field=models.TextField(null=True, verbose_name='Mission'),
        ),
        migrations.AddField(
            model_name='departmentpage',
            name='what_we_do_ar',
            field=models.TextField(help_text='Use service-oriented language and a conversational tone. Try to stay away from jargon and just listing out services.', null=True, verbose_name='What we do'),
        ),
        migrations.AddField(
            model_name='departmentpage',
            name='what_we_do_en',
            field=models.TextField(help_text='Use service-oriented language and a conversational tone. Try to stay away from jargon and just listing out services.', null=True, verbose_name='What we do'),
        ),
        migrations.AddField(
            model_name='departmentpage',
            name='what_we_do_es',
            field=models.TextField(help_text='Use service-oriented language and a conversational tone. Try to stay away from jargon and just listing out services.', null=True, verbose_name='What we do'),
        ),
        migrations.AddField(
            model_name='departmentpage',
            name='what_we_do_vi',
            field=models.TextField(help_text='Use service-oriented language and a conversational tone. Try to stay away from jargon and just listing out services.', null=True, verbose_name='What we do'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='additional_content_ar',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='additional_content_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='additional_content_es',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='additional_content_vi',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='description_ar',
            field=models.TextField(blank=True, null=True, verbose_name='Write a description of this page'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='description_en',
            field=models.TextField(blank=True, null=True, verbose_name='Write a description of this page'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='description_es',
            field=models.TextField(blank=True, null=True, verbose_name='Write a description of this page'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='description_vi',
            field=models.TextField(blank=True, null=True, verbose_name='Write a description of this page'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='options_ar',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['ul', 'ol', 'link'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='options_en',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['ul', 'ol', 'link'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='options_es',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['ul', 'ol', 'link'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='options_vi',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['ul', 'ol', 'link'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.'),
        ),
    ]
