# Generated by Django 2.0.13 on 2019-02-14 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0039_auto_20190214_1458'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpagedirector',
            name='about_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentpagedirector',
            name='about_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentpagedirector',
            name='about_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentpagedirector',
            name='about_vi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
