# Generated by Django 2.0.13 on 2019-02-16 12:56

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0040_auto_20190214_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpage',
            name='what_we_do',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='What we do'),
        ),
        migrations.AlterField(
            model_name='departmentpage',
            name='what_we_do_ar',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='What we do'),
        ),
        migrations.AlterField(
            model_name='departmentpage',
            name='what_we_do_en',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='What we do'),
        ),
        migrations.AlterField(
            model_name='departmentpage',
            name='what_we_do_es',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='What we do'),
        ),
        migrations.AlterField(
            model_name='departmentpage',
            name='what_we_do_vi',
            field=wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='What we do'),
        ),
    ]
