# Generated by Django 2.0.13 on 2019-03-19 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0042_auto_20190313_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='department',
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Topic', verbose_name='Select a Topic'),
        ),
        migrations.AlterField(
            model_name='processpage',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.Topic', verbose_name='Select a Topic'),
        ),
    ]
