# Generated by Django 2.0.13 on 2019-03-21 06:41

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0043_auto_20190319_0618'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='social_media',
            field=wagtail.core.fields.StreamField([('URL', wagtail.core.blocks.TextBlock('Social Media Url'))], blank=True, help_text='For example: https://www.facebook.com/atxpoliceoversight/', verbose_name='Paste links to any social media pages'),
        ),
    ]
