# Generated by Django 2.0.13 on 2019-03-21 06:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0044_contact_social_media'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentpage',
            name='social_media',
        ),
        migrations.AlterField(
            model_name='contact',
            name='social_media',
            field=wagtail.core.fields.StreamField([('url', wagtail.core.blocks.URLBlock(label='Social media url'))], blank=True, help_text='For example: https://www.facebook.com/atxpoliceoversight/', verbose_name='Paste links to any social media pages'),
        ),
    ]
