# Generated by Django 2.0.13 on 2019-03-28 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0045_auto_20190321_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentpagedirector',
            name='email',
        ),
        migrations.RemoveField(
            model_name='departmentpagedirector',
            name='phone',
        ),
        migrations.AddField(
            model_name='departmentpagedirector',
            name='title',
            field=models.CharField(default='Director', max_length=255),
        ),
    ]
