# Generated by Django 2.0.13 on 2019-03-28 09:45

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0047_departmentpage_top_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='social_media',
            field=wagtail.core.fields.StreamField([('url', wagtail.core.blocks.URLBlock(label='Social media url'))], blank=True, help_text='For example: https://www.facebook.com/atxpoliceoversight/', verbose_name='Links to any social media pages'),
        ),
        migrations.AlterField(
            model_name='departmentpage',
            name='top_services',
            field=wagtail.core.fields.StreamField([('link', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('title', wagtail.core.blocks.CharBlock())], icon='link'))], blank=True, verbose_name='Links to top services'),
        ),
    ]
