# Generated by Django 2.0.13 on 2019-03-28 09:54

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0048_auto_20190328_0945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpage',
            name='top_services',
            field=wagtail.core.fields.StreamField([('link_en', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('title', wagtail.core.blocks.CharBlock())], icon='link', label='Link [EN]')), ('link_es', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('title', wagtail.core.blocks.CharBlock())], icon='link', label='Link [ES]')), ('link_ar', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('title', wagtail.core.blocks.CharBlock())], icon='link', label='Link [AR]')), ('link_vi', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('title', wagtail.core.blocks.CharBlock())], icon='link', label='Link [VI]'))], blank=True, verbose_name='Links to top services'),
        ),
    ]
