# Generated by Django 2.0.13 on 2019-03-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0049_auto_20190328_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpagedirector',
            name='title_ar',
            field=models.CharField(default='Director', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departmentpagedirector',
            name='title_en',
            field=models.CharField(default='Director', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departmentpagedirector',
            name='title_es',
            field=models.CharField(default='Director', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='departmentpagedirector',
            name='title_vi',
            field=models.CharField(default='Director', max_length=255, null=True),
        ),
    ]
