# Generated by Django 2.0.13 on 2019-04-03 10:39

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0050_auto_20190328_1156'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationPageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProcessPageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServicePageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='informationpage',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='processpage',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='topic',
        ),
        migrations.AddField(
            model_name='servicepagetopic',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='base.ServicePage'),
        ),
        migrations.AddField(
            model_name='servicepagetopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Topic', verbose_name='Select a Topic'),
        ),
        migrations.AddField(
            model_name='processpagetopic',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='base.ProcessPage'),
        ),
        migrations.AddField(
            model_name='processpagetopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Topic', verbose_name='Select a Topic'),
        ),
        migrations.AddField(
            model_name='informationpagetopic',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='base.InformationPage'),
        ),
        migrations.AddField(
            model_name='informationpagetopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Topic', verbose_name='Select a Topic'),
        ),
    ]
