# Generated by Django 2.0.13 on 2019-04-04 07:52

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('base', '0051_auto_20190403_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('description_ar', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('description_vi', models.TextField(null=True)),
                ('call_to_action', models.TextField(blank=True)),
                ('call_to_action_ar', models.TextField(blank=True, null=True)),
                ('call_to_action_en', models.TextField(blank=True, null=True)),
                ('call_to_action_es', models.TextField(blank=True, null=True)),
                ('call_to_action_vi', models.TextField(blank=True, null=True)),
                ('external_services', wagtail.core.fields.StreamField([('link_en', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('title', wagtail.core.blocks.CharBlock())], icon='link', label='Link [EN]')), ('link_es', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('title', wagtail.core.blocks.CharBlock())], icon='link', label='Link [ES]')), ('link_ar', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('title', wagtail.core.blocks.CharBlock())], icon='link', label='Link [AR]')), ('link_vi', wagtail.core.blocks.StructBlock([('url', wagtail.core.blocks.URLBlock()), ('title', wagtail.core.blocks.CharBlock())], icon='link', label='Link [VI]'))], blank=True, verbose_name='External links to services')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topicPages', to='base.Theme')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
    ]
