# Generated by Django 2.0.13 on 2019-04-11 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0052_topicpage'),
        ('base', '0051_auto_20190410_1344'),
    ]

    operations = [
    ]
