# Generated by Django 2.0.13 on 2019-04-11 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0053_merge_20190411_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicpage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='topicpage',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicpage',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicpage',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='topicpage',
            name='description_vi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
