# Generated by Django 2.0.13 on 2019-04-16 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0055_auto_20190411_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpage',
            name='toplink',
        ),
        migrations.AddField(
            model_name='informationpagetopic',
            name='toplink',
            field=models.BooleanField(default=False, verbose_name='Make this page a top link for this topic'),
        ),
        migrations.AddField(
            model_name='servicepagetopic',
            name='toplink',
            field=models.BooleanField(default=False, verbose_name='Make this service a top link for this topic'),
        ),
    ]
