# Generated by Django 2.0.13 on 2019-04-16 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0056_auto_20190416_1234'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicpage',
            name='call_to_action',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='call_to_action_ar',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='call_to_action_en',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='call_to_action_es',
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='call_to_action_vi',
        ),
    ]
