# Generated by Django 2.0.13 on 2019-04-17 13:24

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('base', '0057_auto_20190416_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCollectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_vi', models.TextField(blank=True, null=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.TranslatedImage')),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='topicPages', to='base.Theme')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='TopicCollectionPageTopicCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topiccollections', to='base.TopicCollectionPage')),
                ('topiccollection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.TopicCollectionPage', verbose_name='Select a Topic Collection')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TopicPageTopicCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='topicpage',
            name='theme',
        ),
        migrations.AddField(
            model_name='topicpagetopiccollection',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topiccollections', to='base.TopicPage'),
        ),
        migrations.AddField(
            model_name='topicpagetopiccollection',
            name='topiccollection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.TopicCollectionPage', verbose_name='Select a Topic Collection'),
        ),
    ]
