# Generated by Django 2.0.13 on 2019-04-17 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0058_auto_20190417_1324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topiccollectionpage',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='topicPages', to='base.Theme'),
        ),
    ]
