# Generated by Django 2.0.13 on 2019-04-18 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0059_remove_servicepage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpage',
            name='image',
        ),
    ]
