# Generated by Django 2.0.13 on 2019-04-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0060_remove_informationpage_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='short_description',
            field=models.TextField(blank=True, max_length=255, verbose_name='Write a description of this service'),
        ),
    ]
