# Generated by Django 2.2.1 on 2019-05-16 09:09

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0063_auto_20190516_0319'),
    ]

    operations = [
        migrations.AddField(
            model_name='translatedimage',
            name='file_hash',
            field=models.CharField(blank=True, editable=False, max_length=40),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='options',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'h6'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', verbose_name='Add option sections as needed.'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='options_ar',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'h6'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='options_en',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'h6'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='options_es',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'h6'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='options_vi',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h1', 'h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'h6'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.'),
        ),
    ]
