# Generated by Django 2.2.1 on 2019-05-22 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0065_auto_20190516_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='short_description_ar',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Write a description of this service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Write a description of this service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='short_description_es',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Write a description of this service'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='short_description_vi',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Write a description of this service'),
        ),
    ]
