# Generated by Django 2.2.1 on 2019-05-22 08:40

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0066_auto_20190522_0558'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpage',
            name='author_notes',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Notes for authors (Not visible on the resident facing site)'),
        ),
        migrations.AddField(
            model_name='informationpage',
            name='author_notes',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Notes for authors (Not visible on the resident facing site)'),
        ),
        migrations.AddField(
            model_name='processpage',
            name='author_notes',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Notes for authors (Not visible on the resident facing site)'),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='author_notes',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Notes for authors (Not visible on the resident facing site)'),
        ),
        migrations.AddField(
            model_name='topiccollectionpage',
            name='author_notes',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Notes for authors (Not visible on the resident facing site)'),
        ),
        migrations.AddField(
            model_name='topicpage',
            name='author_notes',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Notes for authors (Not visible on the resident facing site)'),
        ),
    ]
