# Generated by Django 2.2.2 on 2019-06-04 19:41

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_servicepage_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_ar',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?', null=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_en',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?', null=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?', null=True),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_vi',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?', null=True),
        ),
    ]
