# Generated by Django 2.2.1 on 2019-05-30 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0068_servicepage_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='short_description',
            field=models.TextField(blank=True, max_length=300, verbose_name='Write a description of this service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='short_description_ar',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Write a description of this service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='short_description_en',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Write a description of this service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='short_description_es',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Write a description of this service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='short_description_vi',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='Write a description of this service'),
        ),
    ]
