# Generated by Django 2.2.2 on 2019-06-04 21:24

from django.db import migrations
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0072_auto_20190604_2045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?', verbose_name='Write any additional content describing the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_ar',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?', null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_en',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?', null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_es',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?', null=True, verbose_name='Write any additional content describing the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='additional_content_vi',
            field=wagtail.core.fields.RichTextField(blank=True, help_text='Section header: What else do I need to know?', null=True, verbose_name='Write any additional content describing the service'),
        ),
    ]
