# Generated by Django 2.2.2 on 2019-06-05 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0069_auto_20190530_2220'),
        ('base', '0073_auto_20190604_2124'),
    ]

    operations = [
    ]
