# Generated by Django 2.2.2 on 2019-06-12 16:23

from django.db import migrations, models
import django.utils.timezone
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0075_formfield_formpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='formpage',
            name='author_notes',
            field=wagtail.core.fields.RichTextField(blank=True, verbose_name='Notes for authors (Not visible on the resident facing site)'),
        ),
        migrations.AddField(
            model_name='formpage',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='formpage',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
