# Generated by Django 2.2.3 on 2019-07-10 18:51

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0076_auto_20190710_1845'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePageRelatedDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.DepartmentPage')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_departments', to='base.ServicePage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='ServicePageDepartments',
        ),
    ]
