# Generated by Django 2.2.3 on 2019-07-27 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_informationpagerelateddepartments_servicepagerelateddepartments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='informationpage',
            name='department',
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='department',
        ),
    ]
