# Generated by Django 2.2.3 on 2019-07-10 19:02

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0077_auto_20190710_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepage',
            name='department',
            field=modelcluster.fields.ParentalKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='related_departments', to='base.DepartmentPage'),
        ),
    ]
