# Generated by Django 2.2.3 on 2019-08-02 22:13

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('base', '0077_informationpagerelateddepartments_servicepagerelateddepartments'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficialDocumentPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_notes', wagtail.core.fields.RichTextField(blank=True, verbose_name='Notes for authors (Not visible on the resident facing site)')),
                ('description', models.TextField(blank=True)),
                ('description_ar', models.TextField(blank=True, null=True)),
                ('description_en', models.TextField(blank=True, null=True)),
                ('description_es', models.TextField(blank=True, null=True)),
                ('description_vi', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='OfficialDocumentPageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toplink', models.BooleanField(default=False, verbose_name='Make this list a top link for this topic')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='base.OfficialDocumentPage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.TopicPage', verbose_name='Select a Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficialDocumentPageRelatedDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_departments', to='base.OfficialDocumentPage')),
                ('related_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.DepartmentPage')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OfficialDocumentPageOfficialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('date', models.DateField(null=True, verbose_name='Document date')),
                ('title', models.CharField(max_length=255, verbose_name='Document title')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='Document title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Document title')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='Document title')),
                ('title_vi', models.CharField(max_length=255, null=True, verbose_name='Document title')),
                ('authoring_office', models.CharField(max_length=255, verbose_name='Authoring office of document')),
                ('authoring_office_ar', models.CharField(max_length=255, null=True, verbose_name='Authoring office of document')),
                ('authoring_office_en', models.CharField(max_length=255, null=True, verbose_name='Authoring office of document')),
                ('authoring_office_es', models.CharField(max_length=255, null=True, verbose_name='Authoring office of document')),
                ('authoring_office_vi', models.CharField(max_length=255, null=True, verbose_name='Authoring office of document')),
                ('summary', models.TextField(help_text='600 char limit', max_length=600, verbose_name='Document summary')),
                ('summary_ar', models.TextField(help_text='600 char limit', max_length=600, null=True, verbose_name='Document summary')),
                ('summary_en', models.TextField(help_text='600 char limit', max_length=600, null=True, verbose_name='Document summary')),
                ('summary_es', models.TextField(help_text='600 char limit', max_length=600, null=True, verbose_name='Document summary')),
                ('summary_vi', models.TextField(help_text='600 char limit', max_length=600, null=True, verbose_name='Document summary')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Document')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='Name of Document')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name of Document')),
                ('name_es', models.CharField(max_length=255, null=True, verbose_name='Name of Document')),
                ('name_vi', models.CharField(max_length=255, null=True, verbose_name='Name of Document')),
                ('link', models.URLField(verbose_name='Link to Document (URL)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_documents', to='base.OfficialDocumentPage')),
            ],
        ),
        migrations.AddIndex(
            model_name='officialdocumentpageofficialdocument',
            index=models.Index(fields=['-date'], name='base_offici_date_9cfd76_idx'),
        ),
    ]
