# Generated by Django 2.2.3 on 2019-08-02 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_auto_20190727_1510'),
        ('base', '0078_create_officialdocumentpage'),
    ]

    operations = [
    ]
