# Generated by Django 2.2.3 on 2019-07-26 22:51

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0078_create_officialdocumentpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdocumentpage',
            name='documents',
            field=wagtail.core.fields.StreamField([('document', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.CharBlock()), ('title', wagtail.core.blocks.CharBlock()), ('authoring_office', wagtail.core.blocks.CharBlock()), ('summary', wagtail.core.blocks.CharBlock()), ('name', wagtail.core.blocks.CharBlock()), ('link', wagtail.core.blocks.CharBlock())]))], blank=True, verbose_name='Entries will be listed by document date (newest first).'),
        ),
    ]
