# Generated by Django 2.2.4 on 2019-08-05 22:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_merge_20190802_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='theme',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='theme', to='base.Theme'),
        ),
    ]
