# Generated by Django 2.2.3 on 2019-07-04 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_auto_20190704_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentowners',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.DepartmentPage'),
        ),
    ]
