# Generated by Django 2.2.3 on 2019-07-10 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_remove_servicepage_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='department',
            field=models.ManyToManyField(blank=True, null=True, to='base.DepartmentPage', verbose_name='Select a Department'),
        ),
    ]
