# Generated by Django 2.2.3 on 2019-07-27 23:19

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0079_officialdocumentpage_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialdocumentpage',
            name='documents',
            field=wagtail.core.fields.StreamField([('document', wagtail.core.blocks.StructBlock([('date', wagtail.core.blocks.DateBlock(label='Document date')), ('title', wagtail.core.blocks.CharBlock(label='Document title')), ('authoring_office', wagtail.core.blocks.CharBlock(label='Authoring office of document')), ('summary', wagtail.core.blocks.TextBlock(label='Document summary')), ('name', wagtail.core.blocks.CharBlock(label='Name of Document')), ('link', wagtail.core.blocks.URLBlock(label='Link to Document (URL)'))]))], blank=True, verbose_name='Entries will be listed by document date (newest first).'),
        ),
    ]
