# Generated by Django 2.2.4 on 2019-08-05 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_servicepage_theme'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='theme',
        ),
    ]
