# Generated by Django 2.2.3 on 2019-07-05 22:34

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0080_auto_20190704_2338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentowners',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_owners', to='wagtailcore.Page'),
        ),
    ]
