# Generated by Django 2.2.4 on 2019-08-21 22:36

from django.db import migrations
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_auto_20190807_1916'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicepage',
            name='related_topics',
            field=modelcluster.fields.ParentalManyToManyField(blank=True, to='base.TopicPage'),
        ),
    ]
