# Generated by Django 2.2.3 on 2019-07-10 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0081_auto_20190710_1920'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepage',
            name='department',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete='PROTECT', to='base.DepartmentPage', verbose_name='Select a Department'),
        ),
    ]
