# Generated by Django 2.2.4 on 2019-09-02 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='departmentpage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='departmentpage',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentpage',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentpage',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='departmentpage',
            name='description_vi',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='description_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='description_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicepage',
            name='description_vi',
            field=models.TextField(blank=True, null=True),
        ),
    ]
