# Generated by Django 2.2.4 on 2019-08-28 07:29

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('base', '0082_phonenumber'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentpage',
            name='top_services',
        ),
        migrations.CreateModel(
            name='DepartmentPageTopService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('department', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='top_service_pages', to='base.DepartmentPage')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page', verbose_name='Select a page')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
