# Generated by Django 2.2.3 on 2019-07-28 19:55

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0082_auto_20190728_0001'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialdocumentpage',
            name='documents',
        ),
        migrations.CreateModel(
            name='OfficialDocumentPageOfficialDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_order', models.IntegerField(blank=True, editable=False, null=True)),
                ('title', models.CharField(max_length=255, verbose_name='Document title')),
                ('title_ar', models.CharField(max_length=255, null=True, verbose_name='Document title')),
                ('title_en', models.CharField(max_length=255, null=True, verbose_name='Document title')),
                ('title_es', models.CharField(max_length=255, null=True, verbose_name='Document title')),
                ('title_vi', models.CharField(max_length=255, null=True, verbose_name='Document title')),
                ('authoring_office', models.CharField(max_length=255, verbose_name='Authoring office of document')),
                ('summary', models.TextField(help_text='600 char limit', max_length=600, verbose_name='Document summary')),
                ('summary_ar', models.TextField(help_text='600 char limit', max_length=600, null=True, verbose_name='Document summary')),
                ('summary_en', models.TextField(help_text='600 char limit', max_length=600, null=True, verbose_name='Document summary')),
                ('summary_es', models.TextField(help_text='600 char limit', max_length=600, null=True, verbose_name='Document summary')),
                ('summary_vi', models.TextField(help_text='600 char limit', max_length=600, null=True, verbose_name='Document summary')),
                ('name', models.CharField(max_length=255, verbose_name='Name of Document')),
                ('name_ar', models.CharField(max_length=255, null=True, verbose_name='Name of Document')),
                ('name_en', models.CharField(max_length=255, null=True, verbose_name='Name of Document')),
                ('name_es', models.CharField(max_length=255, null=True, verbose_name='Name of Document')),
                ('name_vi', models.CharField(max_length=255, null=True, verbose_name='Name of Document')),
                ('link', models.URLField(verbose_name='Link to Document (URL)')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='official_documents', to='base.OfficialDocumentPage')),
            ],
            options={
                'ordering': ['sort_order'],
                'abstract': False,
            },
        ),
    ]
