# Generated by Django 2.2.3 on 2019-07-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_auto_20190728_1955'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdocumentpageofficialdocument',
            name='date',
            field=models.DateField(null=True, verbose_name='Document date'),
        ),
    ]
