# Generated by Django 2.2.3 on 2019-07-10 19:33

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('base', '0083_auto_20190710_1927'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepagerelateddepartments',
            name='department',
        ),
        migrations.AddField(
            model_name='servicepagerelateddepartments',
            name='related_departments',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='wagtailcore.Page'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='servicepage',
            name='department',
        ),
        migrations.AddField(
            model_name='servicepage',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='base.DepartmentPage', verbose_name='Select a Department'),
        ),
        migrations.AlterField(
            model_name='servicepagerelateddepartments',
            name='page',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='related_departments', to='base.ServicePage'),
        ),
    ]
