# Generated by Django 2.2.4 on 2019-08-20 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_auto_20190812_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phonenumber',
            name='phone_description',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
