# Generated by Django 2.2.4 on 2019-09-02 20:15
from django.db import migrations, models
from django.db.models import F
from django.apps import apps


def mission_to_description(apps, schema_editor):
    DepartmentPage = apps.get_model('base', 'DepartmentPage')
    DepartmentPage.objects.all().update(description=F('mission'))


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0083_auto_20190902_2015'),
    ]

    operations = [
        migrations.RunPython(mission_to_description)
    ]
