# Generated by Django 2.2.4 on 2019-09-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_remove_contact_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officialdocumentpageofficialdocument',
            name='summary',
            field=models.TextField(verbose_name='Document summary'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpageofficialdocument',
            name='summary_ar',
            field=models.TextField(null=True, verbose_name='Document summary'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpageofficialdocument',
            name='summary_en',
            field=models.TextField(null=True, verbose_name='Document summary'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpageofficialdocument',
            name='summary_es',
            field=models.TextField(null=True, verbose_name='Document summary'),
        ),
        migrations.AlterField(
            model_name='officialdocumentpageofficialdocument',
            name='summary_vi',
            field=models.TextField(null=True, verbose_name='Document summary'),
        ),
    ]
