# Generated by Django 2.2.3 on 2019-07-10 19:38

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_auto_20190710_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicepagerelateddepartments',
            name='related_departments',
        ),
        migrations.AddField(
            model_name='servicepagerelateddepartments',
            name='department',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.PROTECT, to='base.DepartmentPage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='servicepagerelateddepartments',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='related_departments', to='base.ServicePage'),
        ),
    ]
