# Generated by Django 2.2.3 on 2019-07-28 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_officialdocumentpageofficialdocument_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='officialdocumentpageofficialdocument',
            options={},
        ),
        migrations.AddIndex(
            model_name='officialdocumentpageofficialdocument',
            index=models.Index(fields=['-date'], name='base_offici_date_9cfd76_idx'),
        ),
    ]
