# Generated by Django 2.2.4 on 2019-09-02 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0084_auto_data_migration_20190902_2015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departmentpage',
            name='description',
            field=models.TextField(blank=True, max_length=400, verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='departmentpage',
            name='description_ar',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='departmentpage',
            name='description_en',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='departmentpage',
            name='description_es',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='departmentpage',
            name='description_vi',
            field=models.TextField(blank=True, max_length=400, null=True, verbose_name='Mission'),
        ),
        migrations.AlterField(
            model_name='departmentpage',
            name='mission',
            field=models.TextField(verbose_name='Mission(old)'),
        ),
        migrations.AlterField(
            model_name='departmentpage',
            name='mission_ar',
            field=models.TextField(null=True, verbose_name='Mission(old)'),
        ),
        migrations.AlterField(
            model_name='departmentpage',
            name='mission_en',
            field=models.TextField(null=True, verbose_name='Mission(old)'),
        ),
        migrations.AlterField(
            model_name='departmentpage',
            name='mission_es',
            field=models.TextField(null=True, verbose_name='Mission(old)'),
        ),
        migrations.AlterField(
            model_name='departmentpage',
            name='mission_vi',
            field=models.TextField(null=True, verbose_name='Mission(old)'),
        ),
    ]
