# Generated by Django 2.2.3 on 2019-07-10 19:44

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_auto_20190710_1938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicepagerelateddepartments',
            old_name='department',
            new_name='related_departments',
        ),
        migrations.AlterField(
            model_name='servicepagerelateddepartments',
            name='page',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_departments', to='base.ServicePage'),
        ),
    ]
