# Generated by Django 2.2.3 on 2019-08-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_auto_20190728_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='officialdocumentpageofficialdocument',
            name='authoring_office_ar',
            field=models.CharField(max_length=255, null=True, verbose_name='Authoring office of document'),
        ),
        migrations.AddField(
            model_name='officialdocumentpageofficialdocument',
            name='authoring_office_en',
            field=models.CharField(max_length=255, null=True, verbose_name='Authoring office of document'),
        ),
        migrations.AddField(
            model_name='officialdocumentpageofficialdocument',
            name='authoring_office_es',
            field=models.CharField(max_length=255, null=True, verbose_name='Authoring office of document'),
        ),
        migrations.AddField(
            model_name='officialdocumentpageofficialdocument',
            name='authoring_office_vi',
            field=models.CharField(max_length=255, null=True, verbose_name='Authoring office of document'),
        ),
    ]
