# Generated by Django 2.2.4 on 2019-09-10 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0085_auto_20190910_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topicpage',
            name='external_services',
        ),
    ]
