# Generated by Django 2.2.3 on 2019-07-10 20:22

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0087_auto_20190710_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicepagerelateddepartments',
            name='page',
            field=modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_departments', to='wagtailcore.Page'),
        ),
    ]
