# Generated by Django 2.2.5 on 2019-09-27 06:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtaildocs', '0010_document_file_hash'),
        ('base', '0089_auto_20190926_1115'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='officialdocumentpageofficialdocument',
            name='link',
        ),
        migrations.AddField(
            model_name='officialdocumentpageofficialdocument',
            name='document',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtaildocs.Document'),
            preserve_default=False,
        ),
    ]
