# Generated by Django 2.2.6 on 2019-10-14 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0092_auto_20191003_1358'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='threeoneone',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='threeoneone',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='threeoneone',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='threeoneone',
            name='title_vi',
        ),
        migrations.AddField(
            model_name='contact',
            name='name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_vi',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_description_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_description_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_description_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_description_vi',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
