# Generated by Django 2.2.5 on 2019-10-21 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('base', '0092_auto_20191003_1358'),
    ]

    operations = [
        migrations.CreateModel(
            name='JanisBranchSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_input', models.CharField(choices=[('url', 'Url'), ('branch_name', 'Branch Name')], default='url', max_length=11, verbose_name='Preview Input Options')),
                ('preview_janis_url', models.URLField(blank=True, help_text='Url of deployed Janis branch to preview pages. Ex: "https://janis.austintexas.io", "localhost:3000" (Don\'t add quotes)', null=True, verbose_name='Preview Janis URL')),
                ('preview_janis_branch', models.TextField(blank=True, help_text='Name of Janis branch to preview pages. Ex: "3000-my-issue-name" (Don\'t add quotes)', null=True, verbose_name='Preview Janis Branch Name')),
                ('publish_janis_branch', models.TextField(blank=True, help_text='Name of Janis branch you want to publish to. Ex: "3000-my-issue-name" (Don\'t add quotes)', null=True, verbose_name='Publish Janis Branch Name')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.Site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
