# Generated by Django 2.2.6 on 2019-10-15 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_auto_20191008_1555'),
        ('base', '0093_auto_20191008_2121'),
    ]

    operations = [
    ]
