# Generated by Django 2.2.5 on 2019-10-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0094_auto_20191014_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='janisbranchsettings',
            name='preview_janis_branch',
            field=models.TextField(blank=True, default=None, help_text='Janis branch to preview pages', null=True),
        ),
    ]
