# Generated by Django 2.2.5 on 2019-10-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0093_janisbranchsettings'),
        ('base', '0094_merge_20191015_2104'),
    ]

    operations = [
    ]
