# Generated by Django 2.2.5 on 2019-10-15 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_auto_20191015_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='janisbranchsettings',
            name='preview_janis_branch',
            field=models.TextField(blank=True, help_text='Janis branch to preview pages', null=True),
        ),
    ]
