# Generated by Django 2.2.6 on 2019-10-31 07:35

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('base', '0096_auto_20191022_2050'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author_notes', wagtail.core.fields.RichTextField(blank=True, verbose_name='Notes for authors (Not visible on the resident facing site)')),
                ('coa_global', models.BooleanField(default=False, verbose_name='Make this a top level page')),
                ('description', models.TextField(blank=True, verbose_name='Form description')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Form description')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Form description')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Form description')),
                ('description_vi', models.TextField(blank=True, null=True, verbose_name='Form description')),
                ('form_url', models.URLField(blank=True, help_text='This link can be found under Share > "Link to this form on your website or email:"', verbose_name='Enter the URL of your Formstack form')),
                ('form_url_ar', models.URLField(blank=True, help_text='This link can be found under Share > "Link to this form on your website or email:"', null=True, verbose_name='Enter the URL of your Formstack form')),
                ('form_url_en', models.URLField(blank=True, help_text='This link can be found under Share > "Link to this form on your website or email:"', null=True, verbose_name='Enter the URL of your Formstack form')),
                ('form_url_es', models.URLField(blank=True, help_text='This link can be found under Share > "Link to this form on your website or email:"', null=True, verbose_name='Enter the URL of your Formstack form')),
                ('form_url_vi', models.URLField(blank=True, help_text='This link can be found under Share > "Link to this form on your website or email:"', null=True, verbose_name='Enter the URL of your Formstack form')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='FormPageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='base.FormPage')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.TopicPage', verbose_name='Select a Topic')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FormPageRelatedDepartments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='related_departments', to='base.FormPage')),
                ('related_department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='base.DepartmentPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
