# Generated by Django 2.2.6 on 2019-10-29 17:43

from django.db import migrations, models
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_auto_20191022_2050'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='map',
            field=wagtail.core.fields.StreamField([('location', wagtail.core.blocks.StructBlock([('marker_description', wagtail.core.blocks.RichTextBlock(default='this would be the place name above')), ('marker_title', wagtail.core.blocks.CharBlock(default='This would be all the address fields above', max_length=120)), ('zoom_level', wagtail.core.blocks.IntegerBlock(default='2', max_value=18, min_value=0, required=False)), ('location_x', wagtail.core.blocks.FloatBlock(default='30.26', required=False)), ('location_y', wagtail.core.blocks.FloatBlock(default='-97.73', required=False)), ('marker_x', wagtail.core.blocks.FloatBlock(default='30.26', required=False)), ('marker_y', wagtail.core.blocks.FloatBlock(default='-97.73', required=False))]))], blank=True),
        ),
        migrations.AddField(
            model_name='location',
            name='map',
            field=wagtail.core.fields.StreamField([('location', wagtail.core.blocks.StructBlock([('marker_description', wagtail.core.blocks.RichTextBlock(default='this would be the place name above')), ('marker_title', wagtail.core.blocks.CharBlock(default='This would be all the address fields above', max_length=120)), ('zoom_level', wagtail.core.blocks.IntegerBlock(default='2', max_value=18, min_value=0, required=False)), ('location_x', wagtail.core.blocks.FloatBlock(default='30.26', required=False)), ('location_y', wagtail.core.blocks.FloatBlock(default='-97.73', required=False)), ('marker_x', wagtail.core.blocks.FloatBlock(default='30.26', required=False)), ('marker_y', wagtail.core.blocks.FloatBlock(default='-97.73', required=False))], marker_description=models.CharField(max_length=255), marker_title=models.TextField(), zoom_level=7))], blank=True),
        ),
    ]
