# Generated by Django 2.2.5 on 2019-10-29 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0096_auto_20191023_2018'),
        ('base', '0096_auto_20191022_2050'),
    ]

    operations = [
    ]
