# Generated by Django 2.2.7 on 2019-11-21 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_formpage_formpagerelateddepartments_formpagetopic'),
    ]

    operations = [
        migrations.AddField(
            model_name='dayandduration',
            name='exceptions',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
