# Generated by Django 2.2.5 on 2019-10-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_auto_20191015_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='janisbranchsettings',
            name='preview_janis_branch',
            field=models.TextField(blank=True, help_text='Name of Janis branch to preview pages (or localhost:[PORT] if running locally). Ex: "3000-my-issue-name", "localhost:3000" (Don\'t add quotes)', null=True),
        ),
        migrations.AlterField(
            model_name='janisbranchsettings',
            name='publish_janis_branch',
            field=models.TextField(blank=True, help_text='Name of Janis branch to publish pages. Ex: "3000-my-issue-name" (Don\'t add quotes)', null=True),
        ),
    ]
