# Generated by Django 2.2.6 on 2019-11-27 19:04

from django.conf import settings
from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0041_group_collection_permissions_verbose_name_plural'),
        ('base', '0097_formpage_formpagerelateddepartments_formpagetopic'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormPage',
            new_name='FormContainer',
        ),
        migrations.RenameModel(
            old_name='FormPageRelatedDepartments',
            new_name='FormContainerRelatedDepartments',
        ),
        migrations.RenameModel(
            old_name='FormPageTopic',
            new_name='FormContainerTopic',
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='options',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'code', 'embed'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', verbose_name='Add option sections as needed.'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='options_ar',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'code', 'embed'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='options_en',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'code', 'embed'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='options_es',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'code', 'embed'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.'),
        ),
        migrations.AlterField(
            model_name='informationpage',
            name='options_vi',
            field=wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'code', 'embed'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps',
            field=wagtail.core.fields.StreamField([('basic_step', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Basic Step')), ('step_with_options_accordian', wagtail.core.blocks.StructBlock([('options_description', wagtail.core.blocks.RichTextBlock(classname='coa-option-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('option_name', wagtail.core.blocks.TextBlock(label='Option name. (When clicked, this name will expand the content for this option')), ('option_description', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Option Content'))])))], label='Step With Options'))], blank=True, help_text='A step may have a basic text step or an options accordion which reveals two or more options', verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps_ar',
            field=wagtail.core.fields.StreamField([('basic_step', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Basic Step')), ('step_with_options_accordian', wagtail.core.blocks.StructBlock([('options_description', wagtail.core.blocks.RichTextBlock(classname='coa-option-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('option_name', wagtail.core.blocks.TextBlock(label='Option name. (When clicked, this name will expand the content for this option')), ('option_description', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Option Content'))])))], label='Step With Options'))], blank=True, help_text='A step may have a basic text step or an options accordion which reveals two or more options', null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps_en',
            field=wagtail.core.fields.StreamField([('basic_step', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Basic Step')), ('step_with_options_accordian', wagtail.core.blocks.StructBlock([('options_description', wagtail.core.blocks.RichTextBlock(classname='coa-option-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('option_name', wagtail.core.blocks.TextBlock(label='Option name. (When clicked, this name will expand the content for this option')), ('option_description', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Option Content'))])))], label='Step With Options'))], blank=True, help_text='A step may have a basic text step or an options accordion which reveals two or more options', null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps_es',
            field=wagtail.core.fields.StreamField([('basic_step', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Basic Step')), ('step_with_options_accordian', wagtail.core.blocks.StructBlock([('options_description', wagtail.core.blocks.RichTextBlock(classname='coa-option-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('option_name', wagtail.core.blocks.TextBlock(label='Option name. (When clicked, this name will expand the content for this option')), ('option_description', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Option Content'))])))], label='Step With Options'))], blank=True, help_text='A step may have a basic text step or an options accordion which reveals two or more options', null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
        migrations.AlterField(
            model_name='servicepage',
            name='steps_vi',
            field=wagtail.core.fields.StreamField([('basic_step', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Basic Step')), ('step_with_options_accordian', wagtail.core.blocks.StructBlock([('options_description', wagtail.core.blocks.RichTextBlock(classname='coa-option-description', features=['ul', 'link', 'code', 'rich-text-button-link'])), ('options', wagtail.core.blocks.ListBlock(wagtail.core.blocks.StructBlock([('option_name', wagtail.core.blocks.TextBlock(label='Option name. (When clicked, this name will expand the content for this option')), ('option_description', wagtail.core.blocks.RichTextBlock(features=['ul', 'link', 'code', 'rich-text-button-link'], label='Option Content'))])))], label='Step With Options'))], blank=True, help_text='A step may have a basic text step or an options accordion which reveals two or more options', null=True, verbose_name='Write out the steps a resident needs to take to use the service'),
        ),
    ]
