# Generated by Django 2.2.6 on 2019-11-19 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0097_formpage_formpagerelateddepartments_formpagetopic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentpage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels')]},
        ),
        migrations.AlterModelOptions(
            name='formpage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels')]},
        ),
        migrations.AlterModelOptions(
            name='guidepage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels')]},
        ),
        migrations.AlterModelOptions(
            name='informationpage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels')]},
        ),
        migrations.AlterModelOptions(
            name='officialdocumentpage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels')]},
        ),
        migrations.AlterModelOptions(
            name='processpage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels')]},
        ),
        migrations.AlterModelOptions(
            name='servicepage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels')]},
        ),
        migrations.AlterModelOptions(
            name='topiccollectionpage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels')]},
        ),
        migrations.AlterModelOptions(
            name='topicpage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels')]},
        ),
    ]
