# Generated by Django 2.2.7 on 2019-11-20 23:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_auto_20191120_2256'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecurringStuff',
            new_name='RecurringRules',
        ),
        migrations.AddField(
            model_name='contact',
            name='exceptions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='base.RecurringRules'),
        ),
    ]
