# Generated by Django 2.2.5 on 2019-10-16 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_auto_20191016_1826'),
    ]

    operations = [
        migrations.AddField(
            model_name='janisbranchsettings',
            name='preview_options',
            field=models.CharField(choices=[('1', 'Url'), ('2', 'Branch Name')], default='Url', max_length=11),
        ),
        migrations.AlterField(
            model_name='janisbranchsettings',
            name='preview_janis_branch',
            field=models.TextField(blank=True, help_text='Name of Janis branch to preview pages (or localhost:[PORT] if running locally). Ex: "3000-my-issue-name", "localhost:3000" (Don\'t add quotes)', null=True, verbose_name='Preview Janis URL'),
        ),
    ]
