# Generated by Django 2.2.6 on 2019-11-22 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_auto_20191119_1842'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departmentpage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels'), ('view_snippets', 'Can view snippets'), ('add_snippets', 'Can add snippet'), ('delete_snippets', 'Can delete snippet')]},
        ),
        migrations.AlterModelOptions(
            name='formpage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels'), ('view_snippets', 'Can view snippets'), ('add_snippets', 'Can add snippet'), ('delete_snippets', 'Can delete snippet')]},
        ),
        migrations.AlterModelOptions(
            name='guidepage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels'), ('view_snippets', 'Can view snippets'), ('add_snippets', 'Can add snippet'), ('delete_snippets', 'Can delete snippet')]},
        ),
        migrations.AlterModelOptions(
            name='informationpage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels'), ('view_snippets', 'Can view snippets'), ('add_snippets', 'Can add snippet'), ('delete_snippets', 'Can delete snippet')]},
        ),
        migrations.AlterModelOptions(
            name='officialdocumentpage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels'), ('view_snippets', 'Can view snippets'), ('add_snippets', 'Can add snippet'), ('delete_snippets', 'Can delete snippet')]},
        ),
        migrations.AlterModelOptions(
            name='processpage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels'), ('view_snippets', 'Can view snippets'), ('add_snippets', 'Can add snippet'), ('delete_snippets', 'Can delete snippet')]},
        ),
        migrations.AlterModelOptions(
            name='servicepage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels'), ('view_snippets', 'Can view snippets'), ('add_snippets', 'Can add snippet'), ('delete_snippets', 'Can delete snippet')]},
        ),
        migrations.AlterModelOptions(
            name='topiccollectionpage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels'), ('view_snippets', 'Can view snippets'), ('add_snippets', 'Can add snippet'), ('delete_snippets', 'Can delete snippet')]},
        ),
        migrations.AlterModelOptions(
            name='topicpage',
            options={'permissions': [('view_extra_panels', 'Can view extra panels'), ('view_snippets', 'Can view snippets'), ('add_snippets', 'Can add snippet'), ('delete_snippets', 'Can delete snippet')]},
        ),
    ]
