# Generated by Django 2.2.7 on 2019-11-21 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0098_dayandduration_exceptions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dayandduration',
            name='exceptions',
        ),
        migrations.AddField(
            model_name='contactdayandduration',
            name='exceptions',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
