# Generated by Django 2.2.5 on 2019-10-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_auto_20191016_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='janisbranchsettings',
            name='publish_janis_branch',
        ),
        migrations.AlterField(
            model_name='janisbranchsettings',
            name='preview_janis_url',
            field=models.URLField(blank=True, help_text='Url of deployed Janis branch to preview pages. Ex: "https://janis.austintexas.io", "localhost:3000" (Don\'t add quotes)', null=True, verbose_name='Preview Janis URL'),
        ),
    ]
