# Generated by Django 2.2.7 on 2019-12-05 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0100_auto_20191121_2000'),
        ('base', '0099_auto_20191203_1807'),
    ]

    operations = [
    ]
