# Generated by Django 2.2.5 on 2019-10-16 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0101_auto_20191016_1858'),
    ]

    operations = [
        migrations.AlterField(
            model_name='janisbranchsettings',
            name='preview_input',
            field=models.CharField(choices=[('1', 'Url'), ('2', 'Branch Name')], default='1', max_length=1, verbose_name='Preview Input Options'),
        ),
    ]
