# Generated by Django 2.2.8 on 2019-12-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0101_merge_20191205_2229'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentLog',
            fields=[
                ('operation', models.CharField(db_index=True, max_length=256, primary_key=True, serialize=False)),
                ('value', models.CharField(blank=True, max_length=256, null=True)),
                ('completed', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
