# Generated by Django 2.2.5 on 2019-10-16 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0102_auto_20191016_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='janisbranchsettings',
            name='publish_janis_branch',
            field=models.TextField(blank=True, help_text='Name of Janis branch you want to publish to. Ex: "3000-my-issue-name" (Don\'t add quotes)', null=True, verbose_name='Publish Janis Branch Name'),
        ),
    ]
