# Generated by Django 2.2.10 on 2020-03-06 11:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformationPage',
            fields=[
                ('janisbasepage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base_page.JanisBasePage')),
                ('description', models.TextField(blank=True, verbose_name='Write a description of this page')),
                ('description_ar', models.TextField(blank=True, null=True, verbose_name='Write a description of this page')),
                ('description_en', models.TextField(blank=True, null=True, verbose_name='Write a description of this page')),
                ('description_es', models.TextField(blank=True, null=True, verbose_name='Write a description of this page')),
                ('description_vi', models.TextField(blank=True, null=True, verbose_name='Write a description of this page')),
                ('options', wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'code', 'embed', 'document-link'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', verbose_name='Add option sections as needed.')),
                ('options_ar', wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'code', 'embed', 'document-link'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.')),
                ('options_en', wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'code', 'embed', 'document-link'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.')),
                ('options_es', wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'code', 'embed', 'document-link'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.')),
                ('options_vi', wagtail.core.fields.StreamField([('option', wagtail.core.blocks.RichTextBlock(features=['h2', 'h3', 'h4', 'bold', 'link', 'ul', 'ol', 'code', 'embed', 'document-link'], label='Option'))], blank=True, help_text='Options are needed when the reader needs to make a choice between a few options, such as ways to fill out a form (online, by phone, in person, etc.).', null=True, verbose_name='Add option sections as needed.')),
                ('additional_content', wagtail.core.fields.RichTextField(blank=True, verbose_name='Write any additional content describing the service')),
                ('additional_content_ar', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service')),
                ('additional_content_en', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service')),
                ('additional_content_es', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service')),
                ('additional_content_vi', wagtail.core.fields.RichTextField(blank=True, null=True, verbose_name='Write any additional content describing the service')),
            ],
            options={
                'abstract': False,
            },
            bases=('base_page.janisbasepage',),
        ),
        migrations.CreateModel(
            name='InformationPageContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='InformationPageTopic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='information_page.InformationPage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
