# Generated by Django 2.2.10 on 2020-03-06 11:41

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('topic_page', '0001_initial'),
        ('base', '0003_auto_20200306_1141'),
        ('information_page', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='informationpagetopic',
            name='topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='topic_page.TopicPage', verbose_name='Select a Topic'),
        ),
        migrations.AddField(
            model_name='informationpagecontact',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='base.Contact'),
        ),
        migrations.AddField(
            model_name='informationpagecontact',
            name='page',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='information_page.InformationPage'),
        ),
    ]
