# Generated by Django 2.2.13 on 2020-06-26 16:07

from django.db import migrations
import json
from pages.official_documents_collection.fixtures.helpers.create_fixture import create_fixture


def copy_official_page_data(apps, schema_editor):
    """
    Official document pages have been split out into Official Document Collections and Official Document Pages
    This function copies the information
    """
    OfficialDocumentPageOld = apps.get_model('official_documents_page.OfficialDocumentPage')

    all_official_document_pages = OfficialDocumentPageOld.objects.all()

    for page in all_official_document_pages.iterator():
        old_page_data = json.loads(page.to_json())
        # we don't need all the page data now that I think of it. do we need the rest besides this?
        page_data = old_page_data.pop("documents", None)
        create_fixture(page_data)


class Migration(migrations.Migration):

    dependencies = [
        ('official_documents_collection', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            copy_official_page_data,
        )
    ]
