# Generated by Django 2.2.13 on 2020-06-26 16:07

from django.db import migrations
import json
from importlib import import_module
from pages.official_documents_collection.fixtures.helpers.create_fixture import create_fixture


def copy_official_page_data(apps, schema_editor):
    """
    Official document pages have been split out into Official Document Collections and Official Document Pages
    This function copies the information
    """

    OfficialDocumentPageOld = import_module('pages.official_documents_page.models').OfficialDocumentPage
    OfficialDocumentCollection = import_module('pages.official_documents_collection.models').OfficialDocumentCollection
    home = import_module('pages.home_page.models').HomePage.objects.first()

    all_official_document_pages = OfficialDocumentPageOld.objects.all()

    for page in all_official_document_pages.iterator():
        page_data = json.loads(page.to_json())
        # we don't need all the page data now that I think of it. do we need the rest besides this?
        page_data.pop("documents", None)
        page_data.pop("content_type", None)
        page_data.pop("path", None)
        page_data.pop("owner", None)  # we might need this.....
        page_data.pop("live_revision", None)  # and this?
        page_data.pop("topics", None) # I definitely need this, but lets see. also now its somehow showing up in the migration
        slug = page_data.pop("slug", None)
        slug = slug + '-copy'
        page_data['slug'] = slug
        page_data.pop("slug_en", None)
        page_data['slug_en'] = slug
        # where did I get this path number? here: http://www.agilosoftware.com/blog/django-treebard-and-wagtail-page-creation/
        page_data['path'] = '%s00%02d' % (home.path, home.numchild + 1)
        print('******* ', page_data)
        new_page = OfficialDocumentCollection(**page_data)
        # create_fixture(page_data)

        # Add it as a child of home
        # home.add_child(instance=new_page)

        # Save our draft
        new_page.save()


class Migration(migrations.Migration):

    dependencies = [
        ('official_documents_collection', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            copy_official_page_data,
        )
    ]
