# Generated by Django 2.2.13 on 2020-06-26 16:07

from django.db import migrations
import json
from pages.official_documents_collection.fixtures.helpers.create_fixture import create_fixture


def copy_official_page_data(apps, schema_editor):
    OfficialDocumentPageOld = apps.get_model('official_documents_page.OfficialDocumentPage')

    all_official_document_pages = OfficialDocumentPageOld.objects.all()

    for page in all_official_document_pages.iterator():
        page_data = json.loads(page.to_json())
        create_fixture(page_data)


class Migration(migrations.Migration):

    dependencies = [
        ('official_documents_collection', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(
            copy_official_page_data,
        )
    ]
