# Generated by Django 2.2.13 on 2020-06-26 16:07

from django.db import migrations
import json
from importlib import import_module
from pages.official_documents_collection.fixtures.helpers.create_fixture import create_fixture


def copy_official_page_data(apps, schema_editor):
    """
    Official document pages have been split out into Official Document Collections and Official Document Pages
    This function copies the information
    """

    OfficialDocumentPageOld = apps.get_model('official_documents_page.OfficialDocumentPage')

    # OfficialDocumentPage = import_module('pages.official_documents_page.models').OfficialDocumentPage
    # HomePage = import_module('pages.home_page.models').HomePage
    HomePage = apps.get_model('home_page.HomePage')
    home = HomePage.objects.first()

    all_official_document_pages = OfficialDocumentPageOld.objects.all()

    for page in all_official_document_pages.iterator():
        # old_page_data = json.loads(page.to_json())
        # we don't need all the page data now that I think of it. do we need the rest besides this?
        # old_page_data.pop("documents", None)
        # print(old_page_data)

        page_data = {
            "imported_revision_id": None,
            "live": True,
            "published": True,
            "parent": home,
            "coa_global": False,
            "title": page.title,
            "slug": page.slug +'copy',
            # "add_topics": {
            #     "topics": old_page_data['topics']
            # },
            "description": page.description,
            "description_es": page.description_es
        }

        print('******* ', page_data)
        # new_page = OfficialDocumentCollection(**page_data)
        create_fixture(page_data)


class Migration(migrations.Migration):

    dependencies = [
        ('official_documents_collection', '0001_initial'),
        ('official_documents_page', '0001_initial'),
        ('home_page', '0002_remove_default_homepage'),
    ]

    operations = [
        migrations.RunPython(
            copy_official_page_data,
        )
    ]
