# Generated by Django 2.2.9 on 2020-02-11 05:03

from django.db import migrations


def create_departments_from_pages(apps, schema_editor):
    DepartmentPage = apps.get_model('base', 'DepartmentPage')
    Department = apps.get_model('groups', 'Department')

    Department.objects.bulk_create(
        Department(name=department_page.title, department_page=department_page)
        for department_page in DepartmentPage.objects.all()
    )


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_departments_from_pages),
    ]
