# Generated by Django 2.2.9 on 2020-02-11 06:56

from django.db import migrations

def create_departments_from_pages(apps, schema_editor):
    DepartmentPage = apps.get_model('base', 'DepartmentPage')
    Department = apps.get_model('groups', 'Department')

    for department_page in DepartmentPage.objects.all():
        Department.objects.create(name=department_page.title, department_page=department_page)

class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_departments_from_pages),
    ]